<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>HPSP131 - Workbook 5 - The General Linear Model: t-tests and ANOVA</title>

<script src="site_libs/header-attrs-2.26/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HPSP131</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1intro.html">1. Intro</a>
</li>
<li>
  <a href="2data.html">2. Data 1</a>
</li>
<li>
  <a href="7GLM.html">3. Data 2</a>
</li>
<li>
  <a href="3plot.html">4. Plot</a>
</li>
<li>
  <a href="4LM1.html">5. ttest_ANOVA</a>
</li>
<li>
  <a href="5LM2.html">6. Cor_Reg</a>
</li>
<li>
  <a href="6mod.html">7. Mod</a>
</li>
<li>
  <a href="8sim22.html">8. Pwr_Med</a>
</li>
<li>
  <a href="9SEM.html">9. SEM</a>
</li>
<li>
  <a href="10mixed.html">10. Mixed</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Extra
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="extra_lists.html">Lists, Matrices, and Indexing</a>
    </li>
    <li>
      <a href="extra_joins.html">Joining data.frames</a>
    </li>
    <li>
      <a href="extra_cleaning.html">Cleaning and Data Preparation</a>
    </li>
    <li>
      <a href="extra_chisquare.html">Chi-square Tests</a>
    </li>
    <li>
      <a href="extra_nonparametric.html">Non-parametric Tests</a>
    </li>
    <li>
      <a href="extra_logistic.html">Logistic Regression</a>
    </li>
    <li>
      <a href="extra_functions.html">Custom Functions</a>
    </li>
    <li>
      <a href="extra_simulation.html">Simulations</a>
    </li>
  </ul>
</li>
<li>
  <a href="exercises.html">Exercises</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">HPSP131 - Workbook 5 - The General Linear
Model: t-tests and ANOVA</h1>

</div>


<div id="objectives" class="section level1">
<h1>Objectives</h1>
<p>The aim of this week is to introduce the General Linear Model (GLM)
in R and provide a practical guide for analysing data with a categorical
IV and and continuous DV. By the end of this workbook, you should be
able to:</p>
<ol style="list-style-type: decimal">
<li>Perform an independent-samples t-test in R.</li>
<li>Perform a paired-samples t-test in R.</li>
<li>Perform a one-way ANOVA in R.</li>
<li>Understand tidyverse functions for summarising data:</li>
</ol>
<ul>
<li><code>group_by()</code></li>
<li><code>summarise()</code></li>
</ul>
<ol start="5" style="list-style-type: decimal">
<li>Plot relationship between data with a categorical IV and continuous
DV, including:</li>
</ol>
<ul>
<li>box plot</li>
<li>violin plot</li>
</ul>
</div>
<div id="class-data" class="section level1">
<h1>Class Data</h1>
<p><a href = files/data_2024.csv download>Click here to download the
data used in these workbooks.</a> (You may need to right-click and
select ‘Save Linked File’ option)</p>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<p><a href = "exercises.html">Click here to download this week’s
exercises.</a></p>
</div>
<div id="content" class="section level1">
<h1>Content</h1>
<div id="before-we-begin" class="section level2">
<h2>Before we begin…</h2>
<p>These are the packages we will be using in this workbook. If you have
been following along with the content each week, this package should
already be installed on your computer. Otherwise, make sure you install
them using <code>install.packages()</code> if you have not used them
before.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<p>Also, something to keep in mind, throughout the next few
demonstrations, whenever we analyse data, we will roughly be following
this procedure:</p>
<ol style="list-style-type: decimal">
<li>Prepare the data for analysis.</li>
<li>Run the statistical test.</li>
<li>Visualise the data.</li>
<li>Write-up analysis.</li>
</ol>
</div>
<div id="the-general-linear-model-in-r" class="section level2">
<h2>The General Linear Model in R</h2>
<p>R has built in functions that performs all the statistical tests we
will be covering this week. Whenever we run an analysis in R (whether it
is a t-test, ANOVA, correlation, regression, etc.), generally, we need
to provide the function with two things:</p>
<ol style="list-style-type: decimal">
<li>The formula we wish to test (more on this below).</li>
<li>The data.frame that holds the data.</li>
</ol>
<p>All functions take the following template:</p>
<p><code>function_name(formula,data)</code></p>
<p>In the next few weeks, we will be covering examples of different
analyses. In almost all cases, the function to conduct these analyses
follows this template:</p>
<div id="formulas" class="section level3">
<h3>Formulas</h3>
<p>Whenever we conduct an analysis in R, we need to write the formula
for the linear model. In general, this takes the following form:</p>
<p><code>dependent_variable ~ independent_variable1 + independent_variable2 + ...</code></p>
<p>The variable on the left of the <code>~</code> symbol is the
dependent variable you are trying to predict, while variables on the
right are your independent variables. The variable names are the same as
the column names in your data.frame. Each independent variable in your
model (if there is more than one) is separated by the <code>+</code>
symbol.</p>
</div>
</div>
<div id="independent-samples-t-test" class="section level2">
<h2>Independent-samples t-test</h2>
<p>As covered in the lecture series, an independent samples t-test is
used to assess the relationship between a categorical IV (with two
levels that is between-subjects) and a continuous DV. In this example,
we test whether people who self-identify as a ‘cat-person’ are more
introverted than those who self-identify as a ‘dog-person’. This is an
‘independent-samples’ t-test because participants in one group are
different to participants in the other group.</p>
<div id="prepare-the-data-for-analysis." class="section level3">
<h3>1. Prepare the data for analysis.</h3>
<p>Click <a
href="http://www.jamescmccroskey.com/measures/introversion.htm">here</a>
for details on the Introversion Scale. To keep things simple, we have
only used 5 items from this scale. Note: as specified in the link, low
scores on this scale indicate higher levels of introversion. Therefore,
to be consistent with the name of the measure, scores have been reversed
in the dataset (i.e., high scores corresponds with high introversion).
Also note: sometimes you will need to reverse code the items yourself,
while we don’t have to do this for this data, I have left the code in
(commented out) that would reverse score an Item 1 - to do this, we use
the <code>recode()</code> function within the <code>mutate()</code>
function.</p>
<pre class="r"><code>data1.clean &lt;- data %&gt;%
  filter(cat.dog != &quot;both&quot;) %&gt;%
  filter(cat.dog != &quot;neither&quot;) %&gt;%
  filter(cat.dog != &quot;&quot;) %&gt;%
  mutate( #introversion1R = recode(introversion1,`1` = 5,`2` = 4,`3`=3,`4` = 2,`5` = 1),
          introvert = introversion2 + introversion5 + introversion7 + introversion8 + introversion10) %&gt;%
  select(cat.dog,introvert)</code></pre>
<p>In the code above, we have removed participants that did not specify
identify as either a “dog-person” or “cat-person”. We have also used the
<code>mutate()</code> function to calculate an overall introversion
score. We have also only selected the variables we need for our analysis
- this step is not strictly necessary, but can help you organise your
data.</p>
</div>
<div id="run-the-statistical-test." class="section level3">
<h3>2. Run the statistical test.</h3>
<p>To run the t-test, we use the function <code>t.test()</code>. As
mentioned above, the first argument is the formula. In this analysis,
the DV is called <code>introvert</code> and the IV is called
<code>cat.dog</code>, so the formula is
<code>introvert ~ cat.dog</code>. The second argument or the
<code>t.test()</code> function is the cleaned data.frame, which we’ve
called <code>data1.clean</code>.</p>
<pre class="r"><code>t.test(introvert ~ cat.dog,data1.clean)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  introvert by cat.dog
## t = -0.10353, df = 96.745, p-value = 0.9178
## alternative hypothesis: true difference in means between group cat and group dog is not equal to 0
## 95 percent confidence interval:
##  -1.409036  1.269330
## sample estimates:
## mean in group cat mean in group dog 
##          15.47917          15.54902</code></pre>
<p>The output from the statistical test gives you a lot of information,
but there are a couple bits that are particularly important:</p>
<ul>
<li>The t-statistic - this is the value for the test statistic (above
this equals -0.1)</li>
<li>The degrees of freedom (above this equals 96.75)</li>
<li>The p-value - this tells you whether the test is significant or not
(above this equals 0.918)</li>
</ul>
<p>Can you see where each of these values come from in the output
above?</p>
</div>
<div id="visualise-the-data." class="section level3">
<h3>3. Visualise the data.</h3>
<div id="box-plot" class="section level4">
<h4>Box Plot</h4>
<p>Box plots are good for representing the range and quantiles of your
data. To create a box plot, use <code>geom_boxplot()</code>. Make sure
to set the correct variables on the x- and y-axes (<code>cat.dog</code>
and <code>introvert</code> respectively). We also map the ‘fill’
aesthetic to the <code>cat.dog</code> variable so that the colours are
different.</p>
<pre class="r"><code>ggplot(data1.clean,aes(x = cat.dog,y = introvert,fill = cat.dog)) +
  geom_boxplot() +
  theme_classic()</code></pre>
<p><img src="4LM1_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="violin-plot" class="section level4">
<h4>Violin Plot</h4>
<p>Violin plots are good for representing the distributions of scores on
the DV between groups, and can be created using
<code>geom_violin()</code>. All aesthetics are identical to the box plot
above. If you want to includes visualisations of each individual data
point, you can use <code>geom_jitter()</code>. You can also visualise
the mean and standard error using the <code>stat_summary()</code>
function.</p>
<pre class="r"><code>ggplot(data1.clean,aes(x = cat.dog,y = introvert,fill = cat.dog)) +
  geom_violin() +
  stat_summary() +
  geom_jitter(width = .1,alpha = .2) +
  theme_classic()</code></pre>
<p><img src="4LM1_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
</div>
<div id="write-up-analysis." class="section level3">
<h3>4. Write-up analysis.</h3>
<p>In order to report a t-test in APA format, we need the following
information:</p>
<ul>
<li>The t-statistic and degrees of freedom (df) for the statistical
test.</li>
<li>the p-value from the statistical test.</li>
<li>The mean on the DV for both groups.</li>
<li>The standard deviations on the DV for both groups.</li>
</ul>
<p>The first three items can be obtained from the output of
<code>t.test()</code> above. However, to get the SDs of the two groups,
we need to cover a few more tidyverse functions.</p>
<p>As covered in Workbook 2, <code>summarise()</code> can be used to get
descriptive statistics by using functions like <code>mean()</code> and
<code>sd()</code> to get the mean and standard deviation of a variable
respectively. However, in order to calculate these statistics separately
for different groups, we need to use the <code>group_by()</code>
function. <code>group_by()</code> will group data based on a column, and
perform all subsequent tidyverse functions separately for each group
until you use the <code>ungroup()</code> function.</p>
<pre class="r"><code>data1.summary &lt;- data1.clean %&gt;%
  group_by(cat.dog) %&gt;%
  summarise(introvert_mean = mean(introvert,na.rm = TRUE),
            introvert_sd = sd(introvert,na.rm = TRUE))

data1.summary</code></pre>
<pre><code>## # A tibble: 2 × 3
##   cat.dog introvert_mean introvert_sd
##   &lt;chr&gt;            &lt;dbl&gt;        &lt;dbl&gt;
## 1 cat               15.5         3.34
## 2 dog               15.5         3.37</code></pre>
<p>Once we have all the required information, we can write-up! A few
things to note about APA formatting:</p>
<ul>
<li>All numerical values are rounded to 2 decimal points, except
p-values which are rounded to 3 decimal points.</li>
<li>All letters indicating stats (e.g., M, SD, t, p) should be
italicised.</li>
</ul>
<blockquote>
<p>An independent-samples t-test found that there was no significant
difference on introversion between cat-people (<em>M</em> = 15.48,
<em>SD</em> = 3.34) and dog-people (<em>M</em> = 15.55, <em>SD</em> =
3.37), <em>t</em>(96.75) = -0.1, <em>p</em> = 0.918.</p>
</blockquote>
<div id="bar-graphs" class="section level4">
<h4>Bar Graphs</h4>
<p>A common way of reporting data from a t-test is a bar graph.
Unfortunately, this is a very uninformative way of presenting data (it
gives no representation for the spread/variability in the data). We
provide the code here so we you can re-create a bar graph if needed, and
know how to read one if you see one in a paper, but then we will never
speak of this evil again. If you need to plot data with a categorical IV
and continuous DV, aim to use a box plot, or better yet a violin
plot.</p>
<p>In a bar graph, the height of the bars represent the mean for each
group. If you’re lucky, you may get error bars, which usually represents
the standard error. In the example below, the error bars represents the
standard error of the mean for each group on the introversion scale.
Note that we have to calculate the standard error ourselves.</p>
<pre class="r"><code>data1.summary &lt;- data1.clean %&gt;%
  group_by(cat.dog) %&gt;%
  summarise(introvert_mean = mean(introvert,na.rm = TRUE),
            introvert_sd = sd(introvert,na.rm = TRUE),
            introvert_se = introvert_sd/sqrt(n()))

ggplot(data1.summary,aes(x = cat.dog,y = introvert_mean,fill = cat.dog)) +
  geom_col() +
  geom_errorbar(aes(ymin = introvert_mean - introvert_se,ymax = introvert_mean + introvert_se),width = .2) +
  theme_classic()</code></pre>
<p><img src="4LM1_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="one-way-between-subjects-anova-analysis-of-variance"
class="section level2">
<h2>One-way Between-Subjects ANOVA (Analysis of Variance)</h2>
<p>The one-way ANOVA is used when you have a continuous DV and a
categorical IV with more than two groups. Let’s revisit the hypothesis
that cat-people are more introverted than dog-people, but what if we did
not exclude participants that reported being ‘both’ or ‘neither’? We
would then have four groups in the IV; therefore, a one-way ANOVA is the
appropriate statistical test.</p>
<div id="prepare-the-data-for-analysis.-1" class="section level3">
<h3>1. Prepare the data for analysis.</h3>
<p>The code below is identical to the code above, except we do not
exclude participants who reported “both” or “neither” (these commands
have been commented out below).</p>
<pre class="r"><code>data3.clean &lt;- data %&gt;%
#  filter(cat.dog != &quot;both&quot;) %&gt;%
#  filter(cat.dog != &quot;neither&quot;) %&gt;%
   filter(cat.dog != &quot;&quot;) %&gt;%
  mutate(introvert = introversion2 + introversion5 + introversion7 + introversion8 + introversion10) %&gt;%
  select(cat.dog,introvert)</code></pre>
</div>
<div id="run-the-statistical-test.-1" class="section level3">
<h3>2. Run the statistical test.</h3>
<p>We run the ANOVA using the <code>aov()</code> function. We can then
pipe it to the <code>summary()</code> function to get interpretable
output.</p>
<pre class="r"><code>aov(introvert ~ cat.dog,data = data3.clean) %&gt;%
  summary()</code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## cat.dog       3   30.9   10.30   0.946  0.421
## Residuals   116 1263.7   10.89</code></pre>
<p>The table above tells us whether there is a significant difference
between any of the groups, but it does not tell us which groups are
significantly different. In order to do this, we need to do follow-up
t-tests. You only need to conduct follow up comparisons if the ANOVA is
significant. Even though we do not find any significant differences
above, we will go through the process anyway from demonstrative
purposes.</p>
<p>In the code below, we run a t.test similar to what we did above.
However, when calling the data, we use the filter function to only
select participants who are in one of two groups. The <code>|</code>
symbol means ‘or’, so below, we are only analysing the data of
participants who are in the dog ‘or’ cat group.</p>
<pre class="r"><code>t.test(introvert ~ cat.dog,data = filter(data3.clean,cat.dog == &quot;dog&quot; | cat.dog == &quot;cat&quot;))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  introvert by cat.dog
## t = -0.10353, df = 96.745, p-value = 0.9178
## alternative hypothesis: true difference in means between group cat and group dog is not equal to 0
## 95 percent confidence interval:
##  -1.409036  1.269330
## sample estimates:
## mean in group cat mean in group dog 
##          15.47917          15.54902</code></pre>
<p>Now, we are only including participants in the dog or both group:</p>
<pre class="r"><code>t.test(introvert ~ cat.dog,data = filter(data3.clean,cat.dog == &quot;dog&quot; | cat.dog == &quot;both&quot;))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  introvert by cat.dog
## t = 0.065972, df = 19.371, p-value = 0.9481
## alternative hypothesis: true difference in means between group both and group dog is not equal to 0
## 95 percent confidence interval:
##  -2.03640  2.16913
## sample estimates:
## mean in group both  mean in group dog 
##           15.61538           15.54902</code></pre>
<p>We continue to repeat this process until we have tested all possible
linear combinations:</p>
<pre class="r"><code>t.test(introvert ~ cat.dog,data = filter(data3.clean,cat.dog == &quot;dog&quot; | cat.dog == &quot;neither&quot;))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  introvert by cat.dog
## t = 1.9715, df = 11.012, p-value = 0.07431
## alternative hypothesis: true difference in means between group dog and group neither is not equal to 0
## 95 percent confidence interval:
##  -0.2381587  4.3361980
## sample estimates:
##     mean in group dog mean in group neither 
##              15.54902              13.50000</code></pre>
<pre class="r"><code>t.test(introvert ~ cat.dog,data = filter(data3.clean,cat.dog == &quot;cat&quot; | cat.dog == &quot;both&quot;))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  introvert by cat.dog
## t = 0.1348, df = 19.67, p-value = 0.8941
## alternative hypothesis: true difference in means between group both and group cat is not equal to 0
## 95 percent confidence interval:
##  -1.974025  2.246461
## sample estimates:
## mean in group both  mean in group cat 
##           15.61538           15.47917</code></pre>
<pre class="r"><code>t.test(introvert ~ cat.dog,data = filter(data3.clean,cat.dog == &quot;cat&quot; | cat.dog == &quot;neither&quot;))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  introvert by cat.dog
## t = 1.8962, df = 11.185, p-value = 0.08405
## alternative hypothesis: true difference in means between group cat and group neither is not equal to 0
## 95 percent confidence interval:
##  -0.3134668  4.2718001
## sample estimates:
##     mean in group cat mean in group neither 
##              15.47917              13.50000</code></pre>
<pre class="r"><code>t.test(introvert ~ cat.dog,data = filter(data3.clean,cat.dog == &quot;both&quot; | cat.dog == &quot;neither&quot;))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  introvert by cat.dog
## t = 1.6488, df = 17.278, p-value = 0.1173
## alternative hypothesis: true difference in means between group both and group neither is not equal to 0
## 95 percent confidence interval:
##  -0.5882034  4.8189726
## sample estimates:
##    mean in group both mean in group neither 
##              15.61538              13.50000</code></pre>
<p>Remember, in your interpretation to adjust the significance level
(alpha) to account for family-wise error rate. Since we conducted six
comparisons, the significance level should be reduced to 0.008 (that is,
.05 divided by 6).</p>
</div>
<div id="visualise-the-data.-1" class="section level3">
<h3>3. Visualise the Data.</h3>
<p>Similar to the independent-samples t-test, we can use a violin plot
to visualise the distributions for each group.</p>
<pre class="r"><code>ggplot(data3.clean,aes(x = cat.dog,y = introvert,fill = cat.dog)) +
  geom_violin() +
  stat_summary() +
  geom_jitter(width = .2,alpha = .2) +
  theme_classic()</code></pre>
<p><img src="4LM1_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="write-up-analysis.-1" class="section level3">
<h3>4. Write-up analysis.</h3>
<p>In order to report a one-way ANOVA in APA format, we need the
following information:</p>
<ul>
<li>The F-statistic for the statistical test.</li>
<li>The Group and Residual degrees-of-freedom.</li>
<li>the p-value from the statistical test.</li>
</ul>
<p>If the ANOVA is significant, then you need to also include the
post-hoc comparisons. For this, you need the following information
(essentially the same as if you were writing up a t-test):</p>
<ul>
<li>The mean on the DV for all groups.</li>
<li>The standard deviations on the DV for both groups.</li>
<li>The test-statistics and p-values from the comparisons.</li>
</ul>
<p>The code below will calculate the mean and standard deviation on the
dependent variable for all groups. It is identical to the code that does
this for the t-test.</p>
<pre class="r"><code>data3.clean %&gt;%
  group_by(cat.dog) %&gt;%
  summarise(dv_mean = mean(introvert,na.rm = TRUE),
            dv_sd = sd(introvert,na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 4 × 3
##   cat.dog dv_mean dv_sd
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1 both       15.6  3.20
## 2 cat        15.5  3.34
## 3 dog        15.5  3.37
## 4 neither    13.5  2.62</code></pre>
<p>Once you have all this information, the write-up becomes:</p>
<blockquote>
<p>A one-way between subjects ANOVA found no significant difference
between groups on introversion, <em>F</em>(3, 116) = 0.95, <em>p</em> =
0.421.</p>
</blockquote>
</div>
</div>
<div id="paired-samples-t-test" class="section level2">
<h2>Paired-samples t-test</h2>
<p>As discussed in the lecture, a paired-samples t-test is like an
independent-samples t-test, except rather than assess two separate
groups of participants (i.e., a between-subjects design), the paired
samples t-test is used when data is collected from the same participant
in two separate conditions (i.e., a within-subjects design). A common
example of this is testing for significant differences in an outcome
variable before and after a treatment or intervention.</p>
<p>In the example below, we test whether mood is influenced by exposure
to a cute cat video. <a
href="https://www.youtube.com/watch?v=1CXmnm_epTM">Click here to see
that video.</a>. We would expect that mood would improve after viewing
the cat video.</p>
<div id="prepare-the-data-for-analysis.-2" class="section level3">
<h3>1. Prepare the data for analysis.</h3>
<p>When conducting a statistical test, we follow the same procedure as
before. First, we must clean the data. Below, we select the columns we
need to run the paired-samples t-test. When running any within-subjects
analysis, we also need to re-shape the data using the
<code>gather()</code> function so that each observation is on a separate
row (rather than each participant). The gather function works by first
specifying a column name that distinguishes between observations made by
the same participant (i.e., between <code>pre.mood</code> and
<code>post.mood</code>), then a variable name that corresponds with the
response (i.e., the number corresponding with mood). Then, you specify
the variables that you want to reshape.</p>
<pre class="r"><code>data2.clean &lt;- data %&gt;%
  filter(!is.na(pre.mood)) %&gt;%
  filter(!is.na(post.mood)) %&gt;%
  select(student.no,pre.mood,post.mood) %&gt;%
  gather(key = &quot;time&quot;,value = &quot;mood&quot;,pre.mood,post.mood) %&gt;%
  mutate(time = factor(time,levels = c(&quot;pre.mood&quot;,&quot;post.mood&quot;)))</code></pre>
<p>Note: The last line above is only used so that the pre-mood and
post-mood variables are in the right order when we plot the data
below.</p>
</div>
<div id="run-the-statistical-test.-2" class="section level3">
<h3>2. Run the statistical test.</h3>
<p>We use the same function as with the independent-samples t-test to
run a paired-samples t-test, the only difference is we must include the
argument ‘paired’ and set it to <code>TRUE</code>.</p>
<pre class="r"><code>t.test(mood ~ time,data = data2.clean,paired = TRUE)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  mood by time
## t = 0.011926, df = 119, p-value = 0.9905
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -6.876366  6.959700
## sample estimates:
## mean difference 
##      0.04166667</code></pre>
<p>Alternatively, if you want to avoid reshaping the data, you can also
use the following technique, but note that the arguments supplied here
are different to almost all other analyses we will be covering in this
module. The first and second arguments are the columns we want to
compare. In this example, this is the ‘before’ and ‘after’ column. How
we specify this is using the following syntax:
<code>data$pre.mood</code>. This is short-hand for specifying the
‘pre.mood’ column in the ‘data’ data.frame. Again, we have to set
‘paired’ to <code>TRUE</code>; however, we do not have to supply a
data.frame. So the code looks like:</p>
<pre class="r"><code>t.test(data$pre.mood,data$post.mood,paired = TRUE)</code></pre>
<pre><code>## 
##  Paired t-test
## 
## data:  data$pre.mood and data$post.mood
## t = 0.011926, df = 119, p-value = 0.9905
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -6.876366  6.959700
## sample estimates:
## mean difference 
##      0.04166667</code></pre>
</div>
<div id="visualise-the-data.-2" class="section level3">
<h3>3. Visualise the data.</h3>
<p>We can plot the data using a violin plot, the same way we visualised
the data for an independent-samples t-test. However, this does not give
an indication of the change in scores within a participant. One way to
represent this graphically, is to plot the data point for each
participant, and include a line between their scores across the two
conditions. We also adjust the opacity of the points and lines using the
<code>alpha</code> aesthetic, just so that the graph isn’t a complete
mess. Note that the graphic below is made with the reshaped data.frame
<code>data2.clean</code>.</p>
<pre class="r"><code>ggplot(data = data2.clean,aes(x = time,y = mood)) +
  geom_violin(aes(fill = time)) +
  stat_summary() +
  geom_point(alpha = .2) +
  geom_line(aes(group = student.no),alpha = .2) +
  xlab(&quot;Exposure Time (Before or After Video)&quot;) +
  ylab(&quot;Mood Rating&quot;) +
  theme(legend.position = &quot;none&quot;) +
  theme_classic()</code></pre>
<p><img src="4LM1_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<div id="write-up-analysis.-2" class="section level3">
<h3>4. Write-up analysis.</h3>
<p>Similar to the independent-samples t-test, we require information on
the mean and standard deviation for each condition. This code is exactly
the same as above.</p>
<pre class="r"><code>data2.summary &lt;- data2.clean %&gt;%
  group_by(time) %&gt;%
  summarise(dv_mean = mean(mood),
            dv_sd = sd(mood))

data2.summary</code></pre>
<pre><code>## # A tibble: 2 × 3
##   time      dv_mean dv_sd
##   &lt;fct&gt;       &lt;dbl&gt; &lt;dbl&gt;
## 1 pre.mood     53.3  28.7
## 2 post.mood    53.3  27.1</code></pre>
<p>Or if you have not reshaped the data:</p>
<pre class="r"><code>data2.summary &lt;- data %&gt;%
  summarise(pre.mean = mean(pre.mood,na.rm = TRUE),
            pre.sd = sd(pre.mood,na.rm = TRUE),
            pst.mean = mean(post.mood,na.rm = TRUE),
            pst.sd = sd(post.mood,na.rm = TRUE))

data2.summary</code></pre>
<pre><code>##   pre.mean   pre.sd pst.mean   pst.sd
## 1   53.325 28.74436 53.28333 27.09528</code></pre>
<blockquote>
<p>A paired-samples t-test found that there was no significant
difference on mood before (<em>M</em> = 53.33, <em>SD</em> = 28.74) and
after (<em>M</em> = 53.28 , <em>SD</em> = 27.1) viewing a cute cat
video, <em>t</em>(119) = 0.01, <em>p</em> = 0.991.</p>
</blockquote>
</div>
</div>
</div>
<div id="exercises-1" class="section level1">
<h1>Exercises</h1>
<p>Now that you’ve completed this week’s workbook, why not give this
week’s exercises a go? You can download the interactive exercises by
clicking the link below.</p>
<p><a href = "exercises.html">Click here to download this week’s
exercises.</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
