<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>HPSP131 - Workbook 6 - The General Linear Model: Correlation and Regression</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<div class="container-fluid main-container">

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HPSP131</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1intro.html">1. Intro</a>
</li>
<li>
  <a href="2data.html">2. Data 1</a>
</li>
<li>
  <a href="7GLM.html">3. Data 2</a>
</li>
<li>
  <a href="3plot.html">4. Plot</a>
</li>
<li>
  <a href="4LM1.html">5. LM1</a>
</li>
<li>
  <a href="5LM2.html">6. LM2</a>
</li>
<li>
  <a href="6mod_med.html">7. Mod Med</a>
</li>
<li>
  <a href="8sim.html">8. Sim</a>
</li>
<li>
  <a href="9SEM.html">9. SEM</a>
</li>
<li>
  <a href="10mixed.html">10. Mixed</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="exercises.html">Exercises</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">HPSP131 - Workbook 6 - The General Linear Model: Correlation and Regression</h1>

</div>


<div id="objectives" class="section level1">
<h1>Objectives</h1>
<p>The aim of this week is to continue working through the General Linear Model (GLM) in R and provide a practical guide for analysing data with a continuous IV and and continuous DV. By the end of this workbook, you should be able to:</p>
<ol style="list-style-type: decimal">
<li>Perform a correlation in R.</li>
<li>Perform a regression in R.</li>
<li>Plot relationship between data with a continuous IV and continuous DV, including:</li>
</ol>
<ul>
<li>scatterplots</li>
</ul>
</div>
<div id="resources" class="section level1">
<h1>Resources</h1>
<p>Here is a list of resources that may help you with this weeks content:</p>
<p><a href = "files/simulated.data_2019.csv" download>Click here to download the data used in these workbooks.</a></p>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<p><a href = "exercises.html">Click here to download this week’s exercises.</a></p>
</div>
<div id="content" class="section level1">
<h1>Content</h1>
<div id="before-we-begin" class="section level2">
<h2>Before we begin…</h2>
<p>We will be using these packages in this weekbook:</p>
<pre class="r"><code>library(tidyverse)
library(lm.beta)</code></pre>
</div>
<div id="correlation" class="section level2">
<h2>Correlation</h2>
<p>As discussed in the lecture, a correlation assesses the relationship between two continuous variables. In the example below, we will assess the association between attitudes towards exercise and intention to exercise (see <a href="https://search.proquest.com/docview/202682863/fulltextPDF/DD04CFC3E9C34772PQ/1?accountid=14755">here</a> for more detail on both scales).</p>
<p>Remember, whenever we analyse data, we will roughly be following this procedure:</p>
<ol style="list-style-type: decimal">
<li>Clean the data for analysis.</li>
<li>Run statistical test</li>
<li>Plot data</li>
<li>Write-up analysis.</li>
</ol>
<div id="clean-the-data-for-analysis." class="section level3">
<h3>1. Clean the data for analysis.</h3>
<p>First, we must calculate the variables we will use in the correlation (summing the items for both scales), and then select the variables in the dataframe.</p>
<pre class="r"><code>data1.clean &lt;- data %&gt;%
  mutate(attitude = exercise.attitude.1 + exercise.attitude.2 + exercise.attitude.3 + exercise.attitude.4 + exercise.attitude.5 + exercise.attitude.6 + exercise.attitude.7 + exercise.attitude.8 + exercise.attitude.9 + exercise.attitude.10 + exercise.attitude.11 + exercise.attitude.12 + exercise.attitude.13 + exercise.attitude.14 + exercise.attitude.15 + exercise.attitude.16 + exercise.attitude.17 + exercise.attitude.18 + exercise.attitude.19,
         intention = exercise.intention.1 + exercise.intention.2 + exercise.intention.3 + exercise.intention.4 + exercise.intention.5 + exercise.intention.6 + exercise.intention.7 + exercise.intention.8 + exercise.intention.9 + exercise.intention.10 + exercise.intention.11) %&gt;%
  dplyr::select(student.no,attitude,intention)</code></pre>
</div>
<div id="run-statistical-test" class="section level3">
<h3>2. Run statistical test</h3>
<p>We run the correlation using the <code>cor.test()</code> function. Similar to analyses we have covered previously, this function requires a formula, and a dataframe.</p>
<p>For a correlation, given that there are no IVs/DVs per se (i.e., we cannot infer causality - do positive attitudes towards exercise lead to increased intentions, or does increased intentions to exercise leads to more positive attitudes?), this is reflected in the formula for a correlation.</p>
<p><code>~ variable1 + variable2</code></p>
<p>Below is the code and output from a correlation conducted in R.</p>
<pre class="r"><code>cor.test(~ attitude + intention,data = data1.clean)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  attitude and intention
## t = 9.1087, df = 107, p-value = 5.294e-15
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.5398797 0.7551031
## sample estimates:
##       cor 
## 0.6608687</code></pre>
</div>
<div id="plot-data" class="section level3">
<h3>3. Plot data</h3>
<div id="scatterplot" class="section level4">
<h4>Scatterplot</h4>
<p>Scatterplots are the best way to visualise correlations, as it allows you to see the raw data and whether you can have confidence in your correlation coefficient. For instance, it can tell you if your significant correlation is due to a small number of outliers.</p>
<p>Usually in a scatterplot, each point represents a single participant, with each variable on the x- and y-axis (this is interchangable).</p>
<p>In the code below, the <code>geom_point()</code> function adds the points on the scatterplot. The <code>geom_smooth()</code> function adds the line-of-best-fit. <code>geom_smooth()</code> requires the additional ‘method’ argument, which tells it what type of line you want. In this instance, we specify “lm” to tell it we want a linear model.</p>
<pre class="r"><code>ggplot(data1.clean,aes(x = attitude,y = intention)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;,formula = y ~ x)</code></pre>
<p><img src="5LM2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
</div>
<div id="write-up-analysis." class="section level3">
<h3>4. Write-up analysis.</h3>
<p>In order to write-up a correlation in APA format, you need the following information:</p>
<ul>
<li>The number of participants.</li>
<li>The correlation coefficient (i.e., the test statistic).</li>
<li>The p-value.</li>
</ul>
<p>Here is an example of a write-up for the correlation above (can you see where each of the numbers came from?):</p>
<blockquote>
<p>There was a significant correlation between attitudes toward exercise and intentions to exercise, <em>r</em>(118) = 0.66, <em>p</em> &lt; .001.</p>
</blockquote>
</div>
</div>
<div id="regression-with-one-predictor" class="section level2">
<h2>Regression with One Predictor</h2>
<p>When running a regression with one predictor (i.e., one IV), this is identical to running a correlation. See the code below and compare it to the correlation above.</p>
<div id="clean-the-data-for-analysis.-1" class="section level3">
<h3>1. Clean the data for analysis.</h3>
<p>This code is identical to the code above.</p>
<pre class="r"><code>data2.clean &lt;- data %&gt;%
  mutate(attitude = exercise.attitude.1 + exercise.attitude.2 + exercise.attitude.3 + exercise.attitude.4 + exercise.attitude.5 + exercise.attitude.6 + exercise.attitude.7 + exercise.attitude.8 + exercise.attitude.9 + exercise.attitude.10 + exercise.attitude.11 + exercise.attitude.12 + exercise.attitude.13 + exercise.attitude.14 + exercise.attitude.15 + exercise.attitude.16 + exercise.attitude.17 + exercise.attitude.18 + exercise.attitude.19,
         intention = exercise.intention.1 + exercise.intention.2 + exercise.intention.3 + exercise.intention.4 + exercise.intention.5 + exercise.intention.6 + exercise.intention.7 + exercise.intention.8 + exercise.intention.9 + exercise.intention.10 + exercise.intention.11) %&gt;%
  dplyr::select(student.no,attitude,intention)</code></pre>
</div>
<div id="run-statistical-test-1" class="section level3">
<h3>2. Run statistical test</h3>
<p>To run a regression, we use the <code>lm()</code> function, which stands for ‘linear model’. Again, the first argument of this function is the analysis formula, and the second is the data.frame being analysed. For the formula, we revert back to the original form with the DV on the right, and predictors on the left.</p>
<pre class="r"><code>#Unstandardised Model
model2 &lt;- lm(intention ~ attitude,data = data2.clean) %&gt;%
summary()

model2</code></pre>
<pre><code>## 
## Call:
## lm(formula = intention ~ attitude, data = data2.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -35.477  -4.834  -0.288   5.374  19.354 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.29626    1.21185  -0.244    0.807    
## attitude     0.39612    0.04349   9.109 5.29e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.522 on 107 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.4367, Adjusted R-squared:  0.4315 
## F-statistic: 82.97 on 1 and 107 DF,  p-value: 5.294e-15</code></pre>
<p>In order to report a regression in APA format, we are required to have standardised coefficients. There are two ways we could do this. First, we could standardise the variables ourselves. Recall from the lecture that to standardise a variable, we need to subtract the mean and divide by the standard deviation. We can use <code>summarise()</code> function (covered in previous weeks) to first get these values.</p>
<pre class="r"><code>#Get means and standard deviation for both variables.
summary.stats &lt;- summarise(data2.clean,
                           intention.mean = mean(intention,na.rm = TRUE),
                           intention.sd = sd(intention,na.rm = TRUE),
                           attitude.mean = mean(attitude,na.rm = TRUE),
                           attitude.sd = sd(attitude,na.rm = TRUE))

summary.stats</code></pre>
<pre><code>##   intention.mean intention.sd attitude.mean attitude.sd
## 1       7.831858     11.16988      20.96429    18.81677</code></pre>
<p>Then, using the <code>mutate()</code> function (again, covered in previous weeks), we can standardise the variables ourselves.</p>
<pre class="r"><code>data2.standardised &lt;- cbind(data2.clean,summary.stats) %&gt;%
  mutate(z.intention = (intention - intention.mean)/intention.sd,
         z.attitude = (attitude - attitude.mean)/attitude.sd)</code></pre>
<p>Then, we then use these standardised variables in the linear regression.</p>
<pre class="r"><code>model2.standardised1 &lt;- lm(z.intention ~ z.attitude,data = data2.standardised) %&gt;%
summary()

model2.standardised1</code></pre>
<pre><code>## 
## Call:
## lm(formula = z.intention ~ z.attitude, data = data2.standardised)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.1761 -0.4328 -0.0258  0.4811  1.7327 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.01578    0.07309   0.216    0.829    
## z.attitude   0.66731    0.07326   9.109 5.29e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.763 on 107 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.4367, Adjusted R-squared:  0.4315 
## F-statistic: 82.97 on 1 and 107 DF,  p-value: 5.294e-15</code></pre>
<p>Alternatively, we can use the <code>lm.beta()</code> function from the lm.beta package. The <code>lm.beta()</code> function takes the original unstandardised model as its first argument, then returns the standardised coefficients. The simplist way to use it is to add it to the pipeline before the <code>summary()</code> function.</p>
<pre class="r"><code>model2.standardised2 &lt;- lm(intention ~ attitude,data = data2.clean) %&gt;%
lm.beta() %&gt;%
summary()

model2.standardised2</code></pre>
<pre><code>## 
## Call:
## lm(formula = intention ~ attitude, data = data2.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -35.477  -4.834  -0.288   5.374  19.354 
## 
## Coefficients:
##             Estimate Standardized Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.29626      0.00000    1.21185  -0.244    0.807    
## attitude     0.39612      0.66087    0.04349   9.109 5.29e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.522 on 107 degrees of freedom
##   (9 observations deleted due to missingness)
## Multiple R-squared:  0.4367, Adjusted R-squared:  0.4315 
## F-statistic: 82.97 on 1 and 107 DF,  p-value: 5.294e-15</code></pre>
<p>Notice that in the summary table above, an additional column named <code>Standardized</code> is added. Also notice that no matter which method you use, the standardised coefficients are the same (once you account for rounding). Everytime you calculate the standardised coefficients, the estimate for the intercept will equal 0. Therefore, you do not need to report the estimated intercept when reporting standardised coefficients.</p>
</div>
<div id="plot-data-1" class="section level3">
<h3>3. Plot data</h3>
<p>With only two variables (one predictor), the plot would be the same as with a correlation, so let’s skip this step just now.</p>
</div>
<div id="write-up-analysis.-1" class="section level3">
<h3>4. Write-up analysis.</h3>
<p>Everything reported in a regression is given in the <code>summary()</code> function. APA guidelines specify that standardised coefficients (betas) should be reported. Therefore, make sure you report the standardised model.</p>
<p>For the model, you need the following information: * the R-squared statistic. * the F-statistic and associated degrees of freedom. * the and p-value for the model.</p>
<p>For each predictor, you need the following information: * the standardised coefficient. * the t-statistic. * the p-value for that coefficient.</p>
<p>Note, if reporting standardised coefficient, there is no need to report the estimate for the intercept (because it is always 0).</p>
<p>So the write-up for the regression above would look something like this below. Again, with only one predictor, the results from a regression is identical to a correlation, so you’re better off reporting it that way to avoid confusion and the extra hassle, but we will go through the write-up below just to demonstrate:</p>
<blockquote>
<p>Linear regression indicated that 43.67% of variance of intention to exercise could be explained by the predictors, (<em>F</em>(1, 107) = 82.97, <em>p</em> &lt; .001). Attitudes significantly predicted intentions to exercise (<em>Beta</em> = 0.66, <em>p</em> = &lt; .001).</p>
</blockquote>
<p>For one or two predictors, it is simple enough to include the coefficients and p-value of predictors in-text like above. However, as your model becomes more complicated, it may be more useful to include a table instead. More on this later.</p>
</div>
</div>
<div id="regression-with-multiple-predictors." class="section level2">
<h2>Regression with Multiple Predictors.</h2>
<p>The real advantage of regression is when there is more than one predictor in the model. In the example below, we run a regression with intention to exercise as the outcome variable, and attitudes to exercise and behavioural control as predictors.</p>
<div id="clean-the-data-for-analysis.-2" class="section level3">
<h3>1. Clean the data for analysis.</h3>
<pre class="r"><code>data3.clean &lt;- data %&gt;%
  mutate(attitude = exercise.attitude.1 + exercise.attitude.2 + exercise.attitude.3 + exercise.attitude.4 + exercise.attitude.5 + exercise.attitude.6 + exercise.attitude.7 + exercise.attitude.8 + exercise.attitude.9 + exercise.attitude.10 + exercise.attitude.11 + exercise.attitude.12 + exercise.attitude.13 + exercise.attitude.14 + exercise.attitude.15 + exercise.attitude.16 + exercise.attitude.17 + exercise.attitude.18 + exercise.attitude.19,
         intention = exercise.intention.1 + exercise.intention.2 + exercise.intention.3 + exercise.intention.4 + exercise.intention.5 + exercise.intention.6 + exercise.intention.7 + exercise.intention.8 + exercise.intention.9 + exercise.intention.10 + exercise.intention.11,
         control = exercise.control.1 + exercise.control.2 + exercise.control.3) %&gt;%
  dplyr::select(student.no,attitude,intention,control)</code></pre>
</div>
<div id="run-statistical-test-2" class="section level3">
<h3>2. Run statistical test</h3>
<pre class="r"><code>#Unstandardised Model
model3 &lt;- lm(intention ~ attitude + control,data = data3.clean)
summary(model3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = intention ~ attitude + control, data = data3.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -31.921  -4.773  -0.327   5.659  18.894 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4.38951    2.88889  -1.519    0.132    
## attitude     0.34612    0.05507   6.285 7.77e-09 ***
## control      0.44408    0.29385   1.511    0.134    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.488 on 104 degrees of freedom
##   (11 observations deleted due to missingness)
## Multiple R-squared:  0.4533, Adjusted R-squared:  0.4428 
## F-statistic: 43.11 on 2 and 104 DF,  p-value: 2.313e-14</code></pre>
<pre class="r"><code>#Standardised Model
lm.beta(model3) %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = intention ~ attitude + control, data = data3.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -31.921  -4.773  -0.327   5.659  18.894 
## 
## Coefficients:
##             Estimate Standardized Std. Error t value Pr(&gt;|t|)    
## (Intercept) -4.38951      0.00000    2.88889  -1.519    0.132    
## attitude     0.34612      0.57857    0.05507   6.285 7.77e-09 ***
## control      0.44408      0.13911    0.29385   1.511    0.134    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.488 on 104 degrees of freedom
##   (11 observations deleted due to missingness)
## Multiple R-squared:  0.4533, Adjusted R-squared:  0.4428 
## F-statistic: 43.11 on 2 and 104 DF,  p-value: 2.313e-14</code></pre>
</div>
<div id="plot-data-2" class="section level3">
<h3>3. Plot data</h3>
<p>It is difficult to plot data from a multiple regression, as, in extreme circumstances, controlling for the variance in one predictor could change the direction of relationship in another. The simplist way is to plot scatterplot for each predictor with the dependent variable separately. If plots don’t appear to map well onto the predicted model - it could indicate you have an issue with your model (e.g., multicollinearity).</p>
<pre class="r"><code>ggplot(data3.clean,aes(x = attitude,y = intention)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="5LM2_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code>ggplot(data3.clean,aes(x = control,y = intention)) +
  geom_point() +
  geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="5LM2_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
<div id="write-up-analysis.-2" class="section level3">
<h3>4. Write-up analysis.</h3>
<p>When reporting regression coefficients in a table, you do not need to report the statistics in-text, though you still need to describe the pattern of results in words.</p>
<blockquote>
<p>We used multiple regression to predict intention to exercise from attitudes to fitness and behavioural control. We found that both predictors explained 45.33% of the variance (<em>F</em>(2, 104) = 43.11, <em>p</em> &lt; .001). Regression coefficients are reported in Table 1. Attitudes to fitness positively predicted intention to exercise. There was no significant effect of behavioural control.</p>
</blockquote>
<p>Table 1. Regression coefficients for linear model predicting intention to exercise.</p>
<table>
<thead>
<tr class="header">
<th>predictor</th>
<th>beta</th>
<th>t</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Attitudes to Fitness</td>
<td>0.58</td>
<td>6.29</td>
<td>&lt; .001</td>
</tr>
<tr class="even">
<td>Behavioural Control</td>
<td>0.14</td>
<td>1.51</td>
<td>0.13</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="exercises-1" class="section level1">
<h1>Exercises</h1>
<p>Now that you’ve completed this week’s workbook, why not give this week’s exercises a go? You can download the interactive exercises by clicking the link below.</p>
<p><a href = "exercises.html">Click here to download this week’s exercises.</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
