<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>HPSP131 - Workbook 7 - Moderation (Interaction Effects) and Mediation</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<div class="container-fluid main-container">

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HPSP131</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1intro.html">1. Intro</a>
</li>
<li>
  <a href="2data.html">2. Data 1</a>
</li>
<li>
  <a href="7GLM.html">3. Data 2</a>
</li>
<li>
  <a href="3plot.html">4. Plot</a>
</li>
<li>
  <a href="4LM1.html">5. LM1</a>
</li>
<li>
  <a href="5LM2.html">6. LM2</a>
</li>
<li>
  <a href="6mod_med2.html">7. Mod Med</a>
</li>
<li>
  <a href="8sim.html">8. Sim</a>
</li>
<li>
  <a href="9SEM.html">9. SEM</a>
</li>
<li>
  <a href="10mixed.html">10. Mixed</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="exercises.html">Exercises</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">HPSP131 - Workbook 7 - Moderation (Interaction Effects) and Mediation</h1>

</div>


<div id="objectives" class="section level1">
<h1>Objectives</h1>
<p>The aim of this week’s workbook is to cover moderation (interaction effects) and mediation analyses in R. By the end of this workbook, you should be able to:</p>
<ol style="list-style-type: decimal">
<li>Perform a multiple regression with interaction effects.</li>
<li>Perform a mediation analysis.</li>
<li>Plot relationship between data with two continuous IVs and one continuous DV, including:</li>
</ol>
<ul>
<li>interaction plots</li>
</ul>
</div>
<div id="class-data" class="section level1">
<h1>Class data</h1>
<p>Here is a list of resources that may help you with this weeks content:</p>
<p><a href = "files/data_2019.csv" download>Click here to download the data used in these workbooks.</a> (You may need to right-click and select ‘Save Linked File’ option)</p>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<p><a href = "exercises.html">Click here to download this week’s exercises.</a></p>
</div>
<div id="content" class="section level1">
<h1>Content</h1>
<div id="before-we-begin" class="section level2">
<h2>Before we begin…</h2>
<p>Remember, whenever we analyse data, we will roughly be following this procedure:</p>
<ol style="list-style-type: decimal">
<li>Clean the data for analysis.</li>
<li>Run the statistical test.</li>
<li>Plot the data.</li>
<li>Write-up analysis.</li>
</ol>
<p>We will be using the following packages. If this is your first time using these packages, remember to install them before loading the packages - we have used all of these packages previously except for the package called <code>psych</code>.</p>
<pre class="r"><code>library(tidyverse)
library(broom)
library(lm.beta)
library(psych)</code></pre>
</div>
<div id="reminder-moderation-interaction-effects" class="section level2">
<h2>Reminder: Moderation (Interaction Effects)</h2>
<p>As covered in the Lecture series, moderation is when the effect of an IV (predictor) on the DV (outcome) depends on another IV (predictor). We can test for an interaction effect in a linear regression.</p>
<p>In the example below, we will test the hypothesis that the association between anxiety about taking a statistical exam and stress is moderated by social support. We would predict that anxiety about taking a statistics exam would cause high stress, but more so for individuals who do not have good social support.</p>
</div>
<div id="regression-with-interaction-effect" class="section level2">
<h2>Regression with Interaction Effect</h2>
<div id="clean-the-data-for-analysis." class="section level3">
<h3>1. Clean the data for analysis.</h3>
<p>First we must calculate the scores for each scale in the analysis from the individual items. As we have done previously, we can do this by using the <code>mutate()</code> function. More information about how these scales are scored can be found in the following research papers:</p>
<p><a href="https://www.sciencedirect.com/science/article/pii/S0191886908000792">For more detail on the Statistic Anxiety Rating Scale (STARS), click here</a>.</p>
<p><a href="https://www.researchgate.net/publication/240290845_The_Multidimensional_Scale_of_Perceived_Social_Support">For more detail on the Perceived Social Support Scale, click here</a>.</p>
<p><a href="https://www.jstor.org/stable/2136404?seq=9#metadata_info_tab_contents">For more detail on the Stress Scale, click here</a>.</p>
<pre class="r"><code>data1.vars &lt;- data %&gt;%
  mutate(stars.test = stars.1 + stars.4 + stars.8 + stars.10 + stars.13 + stars.15 + stars.21 + stars.22,
         support = support.1 + support.2 + support.3 + support.4 + support.5 + support.6 + support.7 + support.8 + support.9 + support.10 + support.11 + support.12,
         stress = stress.1 + stress.2 + stress.3 + stress.4 + stress.5 + stress.6 + stress.7 + stress.8 + stress.9 + stress.10) %&gt;%
  dplyr::select(student.no,stars.test,support,stress)</code></pre>
<p>When including interaction terms in a linear regression, including uncentered variables can be problematic. In order to center the variables, we can use the <code>scale()</code> function. The <code>scale()</code> function expects a numeric vector. There are two additional arguments called <code>center</code> and <code>scale</code>. If <code>center</code> is set to <code>TRUE</code>, but <code>scale</code> is set to <code>FALSE</code>, the <code>scale()</code> function will output the ‘centred’ variable. If both arguments are set to <code>TRUE</code>, the <code>scale()</code> function will return a ‘standardised’ argument.</p>
<p>Because of a quirk with the <code>scale()</code> function, we also need to tell R that the output is a vector. We can do this by piping the results from the <code>scale()</code> function to the <code>as.vector()</code> function.</p>
<p>You can see the <code>scale()</code> function in action below:</p>
<pre class="r"><code>v &lt;- c(3,32,5,6,12,59,96)

#Get the centered variable.

c.v  &lt;- scale(v,center = TRUE,scale = FALSE) %&gt;% as.vector()

c.v</code></pre>
<pre><code>## [1] -27.428571   1.571429 -25.428571 -24.428571 -18.428571  28.571429
## [7]  65.571429</code></pre>
<pre class="r"><code>#Get the standardised variable.

z.v &lt;- scale(v, center = TRUE,scale = TRUE) %&gt;% as.vector()

z.v</code></pre>
<pre><code>## [1] -0.7782022  0.0445845 -0.7214583 -0.6930863 -0.5228546  0.8106273
## [7]  1.8603896</code></pre>
<p>We can use this combination of the <code>scale()</code> and <code>as.vector()</code> functions within the <code>mutate()</code> to calculate the standardised/centred variables of columns in our data.frame:</p>
<pre class="r"><code>#Compute centred variables for analysis.
data1.clean &lt;- mutate(data1.vars,
         c.stars.test = scale(stars.test,center = TRUE,scale = FALSE) %&gt;% as.vector(),
         c.support = scale(support,center = TRUE,scale = FALSE) %&gt;% as.vector()) %&gt;%

#Compute standardised variables.
  mutate(z.stars.test = scale(stars.test,center = TRUE,scale = TRUE) %&gt;% as.vector(),
         z.support = scale(support,center = TRUE,scale = TRUE) %&gt;% as.vector(),
         z.stress = scale(stress,center = TRUE,scale = TRUE) %&gt;% as.vector())</code></pre>
</div>
<div id="run-statistical-test" class="section level3">
<h3>2. Run statistical test</h3>
<p>Recall that interaction effects are the multiplication of the two variable. Therefore, to specify an interaction, we change the formula we specify to include the multiplication of the variable whose interaction we are interested in. For the unstandardised model, make sure you include the centred variables in the formula.</p>
<pre class="r"><code>#Unstandardised Model
model1 &lt;- lm(stress ~ c.stars.test*c.support,data = data1.clean)
summary(model1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = stress ~ c.stars.test * c.support, data = data1.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.2128 -2.0827 -0.0388  1.8891  6.9207 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            23.798183   0.283661  83.897  &lt; 2e-16 ***
## c.stars.test           -0.010807   0.042083  -0.257  0.79782    
## c.support               0.061856   0.021262   2.909  0.00439 ** 
## c.stars.test:c.support  0.003578   0.003150   1.136  0.25863    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.004 on 109 degrees of freedom
##   (5 observations deleted due to missingness)
## Multiple R-squared:  0.08818,    Adjusted R-squared:  0.06308 
## F-statistic: 3.514 on 3 and 109 DF,  p-value: 0.01768</code></pre>
<p>Notice how R automatically includes the main effects in the model? In most cases, you will want to include the separate main effects when including an interaction term, but in the odd occassion when you want to include the interaction effect without the main effect, you can specify it using the <code>:</code> symbol. In other words:</p>
<p><code>stress ~ stars.test*support</code> is identical to <code>stress ~ stars.test + support + stars.test:support</code></p>
<p>Above are the unstandardised coefficients. However, in order to report in APA format, we require the standardised coefficient. Similar to with an ordinary regression, we can use the <code>lm.beta()</code> function to get the standardised coefficients, like here:</p>
<pre class="r"><code>#Standardised Model
lm.beta(model1) %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = stress ~ c.stars.test * c.support, data = data1.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.2128 -2.0827 -0.0388  1.8891  6.9207 
## 
## Coefficients:
##                         Estimate Standardized Std. Error t value Pr(&gt;|t|)
## (Intercept)            23.798183     0.000000   0.283661  83.897  &lt; 2e-16
## c.stars.test           -0.010807    -0.023892   0.042083  -0.257  0.79782
## c.support               0.061856     0.268392   0.021262   2.909  0.00439
## c.stars.test:c.support  0.003578     0.105625   0.003150   1.136  0.25863
##                           
## (Intercept)            ***
## c.stars.test              
## c.support              ** 
## c.stars.test:c.support    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.004 on 109 degrees of freedom
##   (5 observations deleted due to missingness)
## Multiple R-squared:  0.08818,    Adjusted R-squared:  0.06308 
## F-statistic: 3.514 on 3 and 109 DF,  p-value: 0.01768</code></pre>
</div>
<div id="plot-data" class="section level3">
<h3>3. Plot data</h3>
<p>Interactions can often be difficult to intuit from just looking at the numbers in the model. Therefore, it is almost always necessary to plot them. The most common way to plot an interaction is to split the dataset in two according to the moderator: one with participants who score above the mean on the moderator, and the other with participants who score below the mean on the moderator. In our example, this means splitting the data into participants who are above and below the mean in social support. We can do this by creating a new variable using the <code>ifelse()</code> function within the <code>mutate()</code> function.</p>
<p>The <code>ifelse()</code> function works by first specify a condition as the first argument. The second argument is what happens if data from a participant meets that condition. The third arguement is what happens if a participant does not meet that condition. So in the code below, we are creating a new variable called ‘cat.support’. We want to categorise support into two levels, so the condition in the <code>ifelse()</code> function is <code>z.support &gt; 0</code>. Since we standardised the moderator during the cleaning scale. The mean = 0, so we can split the data on this. Participants who meet this condition are in the “high support” group, while those that are not are in the “low support” group.</p>
<pre class="r"><code>plot.data &lt;- mutate(data1.clean,cat.support = ifelse(z.support &gt; 0,&quot;high support&quot;,&quot;low support&quot;)) %&gt;%
  filter(!is.na(cat.support))</code></pre>
<p>We then can plot the regression line adding in a ‘group’ and ‘colour’ aesthetic to separate our data of participants with high and low support.</p>
<pre class="r"><code>ggplot(plot.data,mapping = aes(x = stars.test,y = stress,group = cat.support,colour = cat.support)) +
  geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="6mod_med2_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Even better is if can visualise the raw data in a scatterplot:</p>
<pre class="r"><code>ggplot(plot.data,mapping = aes(x = stars.test,y = stress,group = cat.support,colour = cat.support)) +
  geom_smooth(method = &quot;lm&quot;) +
  geom_point()</code></pre>
<p><img src="6mod_med2_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="write-up-analysis." class="section level3">
<h3>4. Write-up analysis.</h3>
<p>Given that a moderation is exactly the same as a regression, we require the same information to do the write-up. As a reminder, here are the components you need to write up a regression:</p>
<p>For the model, you need the following information:</p>
<ul>
<li>the R-squared statistic.</li>
<li>the F-statistic and associated degrees of freedom.</li>
<li>the p-value for the model.</li>
</ul>
<p>For each predictor, you need the following information:</p>
<ul>
<li>the standardised coefficient.</li>
<li>the t-statistic.</li>
<li>the p-value for that coefficient.</li>
</ul>
<p>As mentioned last week, with more than one predictor in the model, it may make more sense to report the statistics in a table. This includes models with interaction effects (in the case above, the interaction effect is our third predictor).</p>
<p>Here is an example of the write-up:</p>
<blockquote>
<p>We used a linear regression to predict stress from the anxiety about taking a statistics test, level of social support, and the interaction between the two. We found that model explained 8.82% of the variance (F(3,109) = 3.51, p = 0.018). Regression coefficients are reported in Table 1. There was a significant, negative main effect of teaching comprehension on stress. There was no significant main effect of perceived social support on stress. The interaction between comprehension of statistics teacher and level of social support was not significant.</p>
</blockquote>
<p>Table 1. Regression coefficients for linear model predicting stress.</p>
<table>
<thead>
<tr class="header">
<th>predictor</th>
<th>beta</th>
<th>t</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Teacher Comprehension</td>
<td>-0.02</td>
<td>0.04</td>
<td>-0.257</td>
</tr>
<tr class="even">
<td>Social Support</td>
<td>0.27</td>
<td>0.02</td>
<td>2.909</td>
</tr>
<tr class="odd">
<td>TC * SS</td>
<td>0.11</td>
<td>0</td>
<td>1.136</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="mediation" class="section level2">
<h2>Mediation</h2>
<p>As covered in the Lecture series, mediation describes a relationship where the influence of one variable on another can be explained through a third variable. In the example below, we will test whether the relationship between comprehension of a statistics teacher and stress can be explained through individual’s anxiety about taking a statistics exam (i.e., individuals who find statistics teachers hard to understand increase their anxiety about taking statistics tests, which in turn increases stress).</p>
<div id="clean-data-for-analysis." class="section level3">
<h3>1. Clean data for analysis.</h3>
<p>First, we must calculate the variables that we need for our analysis. This process should be fairly familiar by now.</p>
<pre class="r"><code>data2.clean &lt;- data %&gt;%
  mutate(teacher = stars.30 + stars.32 + stars.43 + stars.44 + stars.46,
         support = support.1 + support.2 + support.3 + support.4 + support.5 + support.6 + support.7 + support.8 + support.9 + support.10 + support.11 + support.12,
         stress = stress.1 + stress.2 + stress.3 + stress.4 + stress.5 + stress.6 + stress.7 + stress.8 + stress.9 + stress.10,
         stars.test = stars.1 + stars.4 + stars.8 + stars.10 + stars.13 + stars.15 + stars.21 + stars.22) %&gt;%
  dplyr::select(student.no,teacher,support,stars.test,stress) %&gt;%
  filter(!is.na(teacher)) %&gt;%
  filter(!is.na(stars.test)) %&gt;%
  filter(!is.na(stress))</code></pre>
</div>
<div id="run-statistical-test-1" class="section level3">
<h3>2. Run statistical test</h3>
<p>Remember, mediation is when the effect of one IV could be explained through a third variable (mediation). If there is an effect in a model without the mediator, but that effect is reduced (or disappears) when the mediator is included, there is a chance the mediation is happening. In order to check whether our variables meet these conditions, we need to conduct a number of linear regressions.</p>
<div id="model-1" class="section level4">
<h4>Model 1</h4>
<p>Here, we test whether there is an association between the predictor (teacher comprehension) and the outcome variable (stress):</p>
<pre class="r"><code>lm(stress ~ teacher,data = data2.clean) %&gt;%
  lm.beta() %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = stress ~ teacher, data = data2.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.1611 -2.0385  0.0842  1.8096  7.3295 
## 
## Coefficients:
##             Estimate Standardized Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.65168      0.00000    0.98602  25.001   &lt;2e-16 ***
## teacher     -0.09811     -0.08689    0.10629  -0.923    0.358    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.055 on 112 degrees of freedom
## Multiple R-squared:  0.00755,    Adjusted R-squared:  -0.001311 
## F-statistic: 0.852 on 1 and 112 DF,  p-value: 0.358</code></pre>
</div>
<div id="model-2" class="section level4">
<h4>Model 2</h4>
<p>Here, we test whether including the mediator (anxiety about taking a stats exam) in the model changes the relationship between the predictor (teacher comprehension) and the outcome variable (stress):</p>
<pre class="r"><code>lm(stress ~ teacher + stars.test,data = data2.clean) %&gt;%
  lm.beta() %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = stress ~ teacher + stars.test, data = data2.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.2186 -2.0540  0.0899  1.7750  7.3358 
## 
## Coefficients:
##              Estimate Standardized Std. Error t value Pr(&gt;|t|)    
## (Intercept) 24.483436     0.000000   1.365212  17.934   &lt;2e-16 ***
## teacher     -0.103053    -0.091265   0.110261  -0.935    0.352    
## stars.test   0.007827     0.017483   0.043718   0.179    0.858    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.069 on 111 degrees of freedom
## Multiple R-squared:  0.007837,   Adjusted R-squared:  -0.01004 
## F-statistic: 0.4384 on 2 and 111 DF,  p-value: 0.6462</code></pre>
</div>
<div id="model-3" class="section level4">
<h4>Model 3</h4>
<p>Also, in order for there to be a mediation, we must observe a relationship between the predictor (teacher comprehension) and the mediator (anxiety about taking a stats exam):</p>
<pre class="r"><code>lm(stars.test ~ teacher,data = data2.clean) %&gt;%
  lm.beta() %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = stars.test ~ teacher, data = data2.clean)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -17.2811  -3.7662   0.1951   4.4183  14.3499 
## 
## Coefficients:
##             Estimate Standardized Std. Error t value Pr(&gt;|t|)    
## (Intercept)  21.4953       0.0000     2.1404  10.043  &lt; 2e-16 ***
## teacher       0.6310       0.2502     0.2307   2.735  0.00726 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.633 on 112 degrees of freedom
## Multiple R-squared:  0.06259,    Adjusted R-squared:  0.05422 
## F-statistic: 7.478 on 1 and 112 DF,  p-value: 0.007264</code></pre>
</div>
<div id="mediation-analysis" class="section level4">
<h4>Mediation Analysis</h4>
<p>While we may or may not meet the conditions for a mediation above, we will continue with the analysis to demonstrate the process of conducting a mediation analysis.</p>
<p>In order to conduct a mediation analysis in R, we will load the <code>psych</code> package. If you haven’t installed the <code>psych</code> package yet, make sure to do this before loading the <code>psych</code> package.</p>
<pre class="r"><code>library(psych)</code></pre>
<p>The function that runs the mediation analysis is aptly named <code>mediate()</code>. Like all analysis functions, the <code>mediate()</code> function accepts a formula and a data.frame, but also a couple of options that we will want to change. For the formula, the mediate function takes a specific form, where the mediator is put inside brackets on the right-hand side of the <code>~</code> symbol:</p>
<pre class="r"><code>DV ~ IV + (Mediator)</code></pre>
<p>So for our analysis, the code becomes the following. Note, we also want to set the ‘std’ argument to <code>TRUE</code> to ensure we receive standardised estimates, and the ‘plot’ argument to <code>FALSE</code> so we are only seeing the numeric output (we will see the plot later).</p>
<pre class="r"><code>mediate(stress ~ teacher + (stars.test),data = data2.clean,std = TRUE,plot = FALSE)</code></pre>
<pre><code>## 
## Mediation/Moderation Analysis 
## Call: mediate(y = stress ~ teacher + (stars.test), data = data2.clean, 
##     std = TRUE, plot = FALSE)
## 
## The DV (Y) was  stress . The IV (X) was  teacher . The mediating variable(s) =  stars.test .
## 
## Total effect(c) of  teacher  on  stress  =  -0.09   S.E. =  0.09  t  =  -0.92  df=  112   with p =  0.36
## Direct effect (c&#39;) of  teacher  on  stress  removing  stars.test  =  -0.09   S.E. =  0.1  t  =  -0.93  df=  111   with p =  0.35
## Indirect effect (ab) of  teacher  on  stress  through  stars.test   =  0 
## Mean bootstrapped indirect effect =  0  with standard error =  0.03  Lower CI =  -0.04    Upper CI =  0.06
## R = 0.09 R2 = 0.01   F = 0.44 on 2 and 111 DF   p-value:  0.646 
## 
##  To see the longer output, specify short = FALSE in the print statement or ask for the summary</code></pre>
<p>Most of the information above is what we have encountered previously. The main information we are interested in this output is the line on the mean bootstrapped indirect effect. A large indirect effect (and consequently a greater drop between the total effect and the direct effect) would indicate that mediation is occuring. Since we are bootstrapping, we can tell the significance through confidence intervals. If the range between the lower CI and the upper CI contains zero, then the indirect effect is not significant. If this range does not contain zero, then we have a significant mediation effect.</p>
</div>
</div>
<div id="plot-data-1" class="section level3">
<h3>3. Plot data</h3>
<div id="path-diagram" class="section level4">
<h4>Path Diagram</h4>
<p>For mediation, there’s no good way to plot the raw data that visualises the mediation. The most common way to visualise a mediated effect is through a path diagram. You can do this directly in the <code>mediate()</code> function by setting the ‘plot’ argument to <code>TRUE</code>.</p>
<pre class="r"><code>mediate(stress ~ teacher + (stars.test),data = data2.clean,std = TRUE,plot = TRUE) %&gt;% plot()</code></pre>
<p><img src="6mod_med2_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
</div>
<div id="write-up-analysis.-1" class="section level3">
<h3>4. Write-up analysis.</h3>
<p>There are several things you need to include when writing up a mediation analysis. Writing up a mediation analysis includes the write-up for each individual models with and without the mediator (Model 1 and Model 2 above - these numbers are also included in the output for the <code>mediate()</code> function), and also the estimated indirect effect and associated confidence intervals. Usually, you would want to accompany the write-up with a path diagram such as the one above. It does not make much sense to write-up the analysis above (as we failed to meet the criteria for a mediation in the first instance!), but if we were to do it anyway, it may go something like this:</p>
<blockquote>
<p>In the model where teacher comprehension predicted variance in stress, the effect of teacher comprehension was not significant (beta = -.09, p = 358). When including anxiety about taking a statistics exam into the model, the effect of teacher comprehension did not change (beta = -.09, p = 352). Mediation analysis revealled a non-significant mediating effect of anxiety of taking a statistics exam on the association between teacher comprehension and stress (mean bootstrapped indirect effect = .01, 95% CI = -.05, .06).</p>
</blockquote>
<p>Note: Many of the associations for mediation to occur are not significant above, so this write-up may not make a lot of sense. It is sometimes also easier to report the separate models in a table.</p>
</div>
</div>
</div>
<div id="exercises-1" class="section level1">
<h1>Exercises</h1>
<p>Now that you’ve completed this week’s workbook, why not give this week’s exercises a go? You can download the interactive exercises by clicking the link below.</p>
<p><a href = "exercises.html">Click here to download this week’s exercises.</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
