<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>HPSP131 - Workbook 8 - Custom Functions and Power</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<div class="container-fluid main-container">

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HPSP131</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1intro.html">1. Intro</a>
</li>
<li>
  <a href="2data.html">2. Data 1</a>
</li>
<li>
  <a href="7GLM.html">3. Data 2</a>
</li>
<li>
  <a href="3plot.html">4. Plot</a>
</li>
<li>
  <a href="4LM1.html">5. LM1</a>
</li>
<li>
  <a href="5LM2.html">6. LM2</a>
</li>
<li>
  <a href="6mod_med.html">7. Mod Med</a>
</li>
<li>
  <a href="8sim.html">8. Sim</a>
</li>
<li>
  <a href="9SEM.html">9. SEM</a>
</li>
<li>
  <a href="10mixed.html">10. Mixed</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="exercises.html">Exercises</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">HPSP131 - Workbook 8 - Custom Functions and Power</h1>

</div>


<div id="objectives" class="section level1">
<h1>Objectives</h1>
<p>The aim of this week is to introduce some advance functions that are helpful when programing in R. By the end of this workbook, you should be able to:</p>
<ol style="list-style-type: decimal">
<li>Write your own function.</li>
<li>Simulate a dataset.</li>
<li>Conduct a power analysis via simulation.</li>
</ol>
</div>
<div id="resources" class="section level1">
<h1>Resources</h1>
<p>Here is a list of resources that may help you with this weeks content:</p>
<p><a href = "files/data_2019.csv" download>Click here to download the data used in these workbooks.</a> (You may need to right-click and select ‘Save Linked File’ option)</p>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<p><a href = "exercises.html">Click here to download this week’s exercises.</a></p>
</div>
<div id="content" class="section level1">
<h1>Content</h1>
<p>These are the functions we will be using in this workbook:</p>
<pre class="r"><code>library(tidyverse)
library(broom)</code></pre>
<div id="custom-functions" class="section level2">
<h2>Custom Functions</h2>
<p>Throughout our time with R, we have used many functions from different packages. Functions in these packages were written by other R users. While some of these functions do some complex things, every function in R is written the same way.</p>
<p>To create a function, you will use a function called <code>function()</code>, which has a couple of unique properties. Let’s demonstrate how <code>function()</code> works via an example. Here is a simple function called add_numbers that adds two numbers together.</p>
<pre class="r"><code>add_numbers &lt;- function(number1,number2){
  result &lt;- number1 + number2
  return(result)
}</code></pre>
<p>And here is our new custom function in action:</p>
<pre class="r"><code>add_numbers(number1 = 3, number2 = 4)</code></pre>
<pre><code>## [1] 7</code></pre>
<p>Let’s break these down. The <code>function()</code> function is the function that creates a function. This can be saved as an object (in the example above, the object name is <code>add_numbers</code>). Any arguments you want in your custom functions are named as arguments within the brackets (in the above case, the arguments are <code>number1</code> and <code>number2</code>). <code>function()</code> must always be followed by a set of curly brackets {} which can span multiple lines. Whatever occurs within these curly brackets is performed whenever you call the function. At the end of each function is a <code>return()</code> call, which is what you want your function to return at it’s completion. Each function can only return one object. If your function does not have this command, your function may not do anything.</p>
<p>Importantly, whatever happens inside the function happens in it’s own environment, that is, any objects created inside a function does not get saved in the workspace. So in the example above, we cannot call upon the object <code>result</code> that we made in the function above. If you try, it will produce an error.</p>
<p>Creating custom functions are helpful if you are planning to do the same computation multiple times on different objects. Instead of typing out the code each time, you can write it once in a function, and use that function to perform the operation.</p>
</div>
<div id="standardising-variables" class="section level2">
<h2>Standardising Variables</h2>
<p>Something that we have to perform often is standardising variables (or a vector of numbers). Rather than computing the mean and standard deviation separately everytime we want to do this, we can create a custom function that does the whole process for us.</p>
<p>Here is what the code would look like if we were to standardise a vector manually:</p>
<pre class="r"><code>#This is the vector we wish to standardise.
vector
vector.mean &lt;- mean(vector,na.rm = TRUE)
vector.sd &lt;- sd(vector,na.rm = TRUE)

z.vector &lt;- (vector - vector.mean)/vector.sd</code></pre>
<p>However, we can put this code within the curly brackets of a custom function, and create a new function called <code>z</code>. Remember to use the <code>return()</code> call to tell R that you want the standardised vector to be the output of your new function:</p>
<pre class="r"><code>z &lt;- function(vector){
  vector
  vector.mean &lt;- mean(vector,na.rm = TRUE)
  vector.sd &lt;- sd(vector,na.rm = TRUE)

  z.vector &lt;- (vector - vector.mean)/vector.sd
  return(z.vector)
}</code></pre>
<p>We can now use this function to standardise any vector of numbers we come across! This is particularly helpful to use within a <code>mutate()</code> function while preparing the data for analysis.</p>
</div>
<div id="simulating-a-data.frame-via-a-function" class="section level2">
<h2>Simulating a data.frame via a Function</h2>
<p>Now that we’ve gotten the taste for creating custom functions, let’s create another one that simulates data in a data.frame. We are going to recreate the data.frame from Workbook 5 where we tested the hypothesis that cat-people are more introverted than dog-people. Before we can do that though, we must introduce some new functions:</p>
<p><code>sample()</code></p>
<p>This function randomly samples options from a vector. For instance, below we randomly sample 40 objects who are either in the ‘cat’ group or the ‘dog’ group. To see more about how this function works, read <code>help(sample)</code>.</p>
<pre class="r"><code>sample(c(&quot;cat&quot;,&quot;dog&quot;),40,replace = TRUE)</code></pre>
<pre><code>##  [1] &quot;dog&quot; &quot;cat&quot; &quot;cat&quot; &quot;dog&quot; &quot;cat&quot; &quot;dog&quot; &quot;dog&quot; &quot;cat&quot; &quot;cat&quot; &quot;cat&quot; &quot;dog&quot;
## [12] &quot;dog&quot; &quot;cat&quot; &quot;dog&quot; &quot;dog&quot; &quot;dog&quot; &quot;dog&quot; &quot;cat&quot; &quot;dog&quot; &quot;cat&quot; &quot;cat&quot; &quot;dog&quot;
## [23] &quot;cat&quot; &quot;dog&quot; &quot;dog&quot; &quot;dog&quot; &quot;dog&quot; &quot;cat&quot; &quot;dog&quot; &quot;cat&quot; &quot;cat&quot; &quot;dog&quot; &quot;cat&quot;
## [34] &quot;cat&quot; &quot;cat&quot; &quot;cat&quot; &quot;dog&quot; &quot;cat&quot; &quot;cat&quot; &quot;cat&quot;</code></pre>
<p><code>rnorm()</code></p>
<p>This function creates a random continuous variable that is normally distributed. In the example below, we create a random normal distribution with a mean of 0 and a standard deviation of 1. To see more about how this function works, read <code>help(rnorm)</code>.</p>
<pre class="r"><code>rnorm(40,mean = 0,sd = 1)</code></pre>
<pre><code>##  [1]  0.925922970  0.800012097 -2.106170551 -0.124191644  0.866156356
##  [6]  0.965083146 -0.806967568 -1.105275091 -0.130812914 -1.667304027
## [11]  2.099524222  1.124154557  0.255737336 -1.989511493 -0.570629321
## [16] -2.266888770  1.108130080  0.046372796  0.217378015  0.242768436
## [21] -0.534419178  0.016079400  1.759816101  0.006369869 -1.385132704
## [26]  1.083247433  0.137188277 -1.268768796  1.548538292 -1.791869534
## [31]  0.684711883  0.060870467 -0.770574868 -1.103914827  1.054689455
## [36]  0.579743295 -1.818255320 -2.245511122  1.352286747  0.844875552</code></pre>
<p>We now have the tools to create our simulate data function, which we will save as <code>create_dataset</code>. It will take one argument, n, which specifies the number of participants in the data.frame.</p>
<p>We will set the mean and sd of the variable ‘introvert’ to match what we found in Workbook 4. (<em>M</em> = 36.33, <em>SD</em> = 7.31)</p>
<pre class="r"><code>create_dataset &lt;- function(n){
  result &lt;- data.frame(group = sample(c(&quot;cat&quot;,&quot;dog&quot;),n,replace = TRUE),
                       introvert = rnorm(n,mean = m.introvert,sd = sd.introvert))
  return(result)
}</code></pre>
<p>Let’s test it out:</p>
<pre class="r"><code>create_dataset(20)</code></pre>
<pre><code>##    group introvert
## 1    dog  48.77452
## 2    cat  23.96665
## 3    dog  35.24718
## 4    dog  42.33044
## 5    cat  32.72211
## 6    dog  42.06500
## 7    dog  35.26232
## 8    cat  43.13130
## 9    dog  36.40364
## 10   dog  43.45730
## 11   dog  30.29279
## 12   dog  41.11706
## 13   dog  35.87044
## 14   dog  39.44652
## 15   dog  19.38907
## 16   dog  28.60047
## 17   dog  47.22952
## 18   dog  53.28043
## 19   dog  41.72204
## 20   cat  46.34800</code></pre>
<div id="conduct-a-statistical-test-with-simulated-data." class="section level3">
<h3>Conduct a statistical test with simulated data.</h3>
<p>Let’s expand the function above. How about creating a function that simulates a dataset, then runs a t-test, and returns the results of the test? We can do this by including the function that runs a t.test within the function we wrote above:</p>
<pre class="r"><code>simulate_test &lt;- function(n){
  result &lt;- data.frame(group = sample(c(&quot;cat&quot;,&quot;dog&quot;),n,replace = TRUE),
                       introvert = rnorm(n,mean = m.introvert,sd = sd.introvert))
  test &lt;- t.test(introvert ~ group, data = result) %&gt;%
    tidy()
  return(test$estimate)
}</code></pre>
<pre class="r"><code>simulate_test(20)</code></pre>
<pre><code>## [1] 1.033881</code></pre>
<p>Let’s go another step further and say we want to run a t-tests on simulated data 1000 times. Doing so will give us a distribution of estimates given a certain statistical test and sample size. We can do this by using the <code>replicate()</code> function.</p>
<pre class="r"><code>output_20 &lt;- replicate(1000,simulate_test(20))</code></pre>
<p>To see the distribution of estimates, we can plot these values:</p>
<pre class="r"><code>ggplot() +
  geom_density(aes(output_20))</code></pre>
<p><img src="8sim_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>But hang on! We know there is no effect as the two variables in the t-test are completely random. So how come we are getting such a wide-range of p-values? This demonstrates one of the core issues with statistical tests. A sample is only a proportion of the entire population, and your estimate can vary greatly depending on the slice of the population that happens to make it into your sample.</p>
<p>What if we increase the number of participants in our simulated dataset to 200 participants?</p>
<pre class="r"><code>output_200 &lt;- replicate(1000,simulate_test(200))
ggplot() +
  geom_density(aes(output_200))</code></pre>
<p><img src="8sim_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>We see that, while we still get a range of estimates, they are much less extreme. This is because with a larger sample size, the ‘slice’ that is our sample is more likely to be representative of our population, and therefore is more likely to be around the correct value. Using this knowledge, we can construct a power analysis to determine the minimum number of participants needed to accurately detect an effect.</p>
</div>
</div>
<div id="power-analysis-using-simulations" class="section level2">
<h2>Power analysis using simulations</h2>
<p>Above, we replicated a data.frame where we do not expect to find a significant effect (because the variables are completely random and unrelated from each other). However, what if we expect an association? Using the same technique, we can run a power analysis to determine whether a certain experimental design/analysis has the ability to detect an effect given a sample size.</p>
<p>Remember, power is the ability to detect an effect if it is there. Generally, things that influence power are effect size, alpha level (significance level), and number of observations.</p>
<p>In the code below, we again create a function, but include an additional argument for effect size (in the form of a mean difference between the ‘cat’ and ‘dog’ groups). Also, instead of returning the estimate, we will return the p-value.</p>
<pre class="r"><code>simulate_test2 &lt;- function(n,mean.diff){
  result &lt;- data.frame(group = sample(c(&quot;cat&quot;,&quot;dog&quot;),n,replace = TRUE),
                       introvert = rnorm(n,mean = m.introvert,sd = sd.introvert)) %&gt;%
    mutate_(mean.diff = mean.diff) %&gt;%
    mutate(introvert = ifelse(group == &quot;cat&quot;,introvert - mean.diff/2,introvert + mean.diff/2))
  test &lt;- t.test(introvert~ group, data = result) %&gt;%
    tidy()
  return(test$p.value)
}</code></pre>
<p>Then, we can calculate the proportion of times we find a significant effect when alpha = .05. For fun, let’s use the actual mean difference we found between cat-people and dog-people.</p>
<pre class="r"><code>data &lt;- read.csv(&quot;files/data_2019.csv&quot;,stringsAsFactors = FALSE) %&gt;%
  mutate(introvert = 12 - (introversion1 + introversion4) + introversion2 + introversion5 + introversion7 + introversion8 + introversion10 + introversion11 + introversion13 + introversion14 + introversion16 + introversion18) %&gt;%
  mutate(introvert = introvert * -1)

data %&gt;%
  group_by(cat.dog) %&gt;%
  summarise(introvert.mean = mean(introvert,na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 5 x 2
##   cat.dog introvert.mean
##   &lt;chr&gt;            &lt;dbl&gt;
## 1 &quot;&quot;               NaN  
## 2 both             -35.9
## 3 cat              -33.6
## 4 dog              -38.2
## 5 neither          -34.3</code></pre>
<pre class="r"><code>cat.dog_difference &lt;- -37.67442 - -33.95000</code></pre>
<pre class="r"><code>sim.results &lt;- replicate(1000,simulate_test2(20,cat.dog_difference))

power &lt;- mean(sim.results &lt; .05)

power</code></pre>
<pre><code>## [1] 0.167</code></pre>
<p>The convention is that the analysis is sufficiently powered if it can detect an effect that is present 80% of the time. The power calculated for a sample size of 20 was 16.7%, which falls quite short of this threshold. What if we increased our sample size?</p>
<pre class="r"><code>sim.results &lt;- replicate(1000,simulate_test2(240,cat.dog_difference))

power &lt;- mean(sim.results &lt; .05)

power</code></pre>
<pre><code>## [1] 0.978</code></pre>
<p>Now with a sample size of 240, we appear to have enough power. By running the above simulations at different sample sizes, we will be able to determine the sample sizes needed to acheive 80% power. Below is code to automatically run the <code>simulate_test2()</code> function at different sample sizes and save the results in a data.frame. There are some complicated things going on here, but see if you can make sense of it. You may need to look up what certain functions do.</p>
<pre class="r"><code>power.grid &lt;- data.frame(candidate_n = rep(seq(20,240,by = 20),each = 1000)) %&gt;%
  mutate(power = vapply(candidate_n,simulate_test2,FUN.VALUE = 1,mean.diff = cat.dog_difference)) %&gt;%
  group_by(candidate_n) %&gt;%
  summarise(power = mean(power &lt; .05))

power.grid</code></pre>
<pre><code>## # A tibble: 12 x 2
##    candidate_n power
##          &lt;dbl&gt; &lt;dbl&gt;
##  1          20 0.169
##  2          40 0.353
##  3          60 0.489
##  4          80 0.616
##  5         100 0.707
##  6         120 0.781
##  7         140 0.846
##  8         160 0.903
##  9         180 0.918
## 10         200 0.928
## 11         220 0.956
## 12         240 0.98</code></pre>
<p>This suggests that to detect a mean difference of 3-points on introversion between cat-people and dog-people with our data 80% of the time, we would require between 120 and 140 participants to be confident in our result. We can also plot the simulated power analyses to help determine the sample size required.</p>
<pre class="r"><code>ggplot(data = power.grid,aes(x = candidate_n,y = power)) +
  geom_point() + 
  geom_smooth(colour = &quot;blue&quot;) +
  geom_hline(yintercept = .80,colour = &quot;red&quot;)</code></pre>
<p><img src="8sim_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div id="pwr-package" class="section level2">
<h2>pwr Package</h2>
<p>While the method above is handy for demonstrating some of the capabilities of R, and can be used to do a power analysis for quite complicated analyses, for simple analyses such as an independent-samples t.test, it may be a bit over-kill. A much simpler way to calculate power for standard inferential tests is to use functions in the <code>pwr</code> package. Compare the power estimate above with the one using the <code>pwr.t.test()</code> function below.</p>
<pre class="r"><code>library(pwr)

#First we must calculate effect size (Cohen&#39;s D)

D &lt;- cat.dog_difference/sqrt((sd.introvert^2 + sd.introvert^2)/2)

D</code></pre>
<pre><code>## [1] -0.5093678</code></pre>
<pre class="r"><code>#We then put this effect size into the pwr.t.test() function.

pwr.t.test(d = D,power = .8,sig.level = .05,type = &quot;two.sample&quot;)</code></pre>
<pre><code>## 
##      Two-sample t test power calculation 
## 
##               n = 61.47781
##               d = 0.5093678
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number in *each* group</code></pre>
</div>
</div>
<div id="exercises-1" class="section level1">
<h1>Exercises</h1>
<p>Now that you’ve completed this week’s workbook, why not give this week’s exercises a go? You can download the interactive exercises by clicking the link below.</p>
<p><a href = "exercises.html">Click here to download this week’s exercises.</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
