<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>HPSP131 - Workbook 9 - Path Analysis and Structural Equation Modelling</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HPSP131</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1intro.html">1. Intro</a>
</li>
<li>
  <a href="2data.html">2. Data 1</a>
</li>
<li>
  <a href="7GLM.html">3. Data 2</a>
</li>
<li>
  <a href="3plot.html">4. Plot</a>
</li>
<li>
  <a href="4LM1.html">5. LM1</a>
</li>
<li>
  <a href="5LM2.html">6. LM2</a>
</li>
<li>
  <a href="6mod_med2.html">7. Mod</a>
</li>
<li>
  <a href="8sim.html">8. Power</a>
</li>
<li>
  <a href="9SEM.html">9. SEM</a>
</li>
<li>
  <a href="10mixed.html">10. Mixed</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="exercises.html">Exercises</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">HPSP131 - Workbook 9 - Path Analysis and Structural Equation Modelling</h1>

</div>


<div id="objectives" class="section level1">
<h1>Objectives</h1>
<p>The aim of this week is to introduce the <code>lavaan</code> package for Structural Equation Modelling (e.g., path analysis) in R. By the end of this workbook, you should be familiar with:</p>
<ol style="list-style-type: decimal">
<li>Run a basic mediation analysis.</li>
<li>The basics of the lavaan package.</li>
<li>Run a simple path analysis.</li>
</ol>
</div>
<div id="resources" class="section level1">
<h1>Resources</h1>
<p>Here is a list of resources that may help you with this weeks content:</p>
<p><a href="http://lavaan.ugent.be/tutorial/">lavaan tutorial</a> <a href="http://lavaan.ugent.be/tutorial/tutorial.pdf">lavaan tutorial pdf</a></p>
</div>
<div id="class-data" class="section level1">
<h1>Class Data</h1>
<p><a href = files/simulated.data_2020.csv download>Click here to download the data used in these workbooks.</a> (You may need to right-click and select ‘Save Linked File’ option)</p>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<p><a href = "exercises.html">Click here to download this week’s exercises.</a></p>
</div>
<div id="content" class="section level1">
<h1>Content</h1>
<p>We will be using the following packages in this week’s workbook:</p>
<pre class="r"><code>library(psych)
library(lm.beta)
library(lavaan)
library(tidyverse)
library(semPlot)</code></pre>
<div id="mediation" class="section level2">
<h2>Mediation</h2>
<p>As covered in the Lecture series, mediation describes a relationship where the influence of one variable on another can be explained through a third variable. In the example below, we will test whether the relationship between attitudes towards exercise and exercise behaviour can be explained through intentions to exercise (i.e., individuals who have positive attitudes about exercise increase their intention to exercise, which in turn increases exercise behaviour). For more information on these scales (and some of the ones we will use later), see this paper: <a href="https://search.proquest.com/docview/202682863">https://search.proquest.com/docview/202682863</a>. Note, we only use the first 5-items on each scale to keep things simple.</p>
<div id="clean-data-for-analysis." class="section level3">
<h3>1. Clean data for analysis.</h3>
<p>First, we must calculate the variables that we need for our analysis. This process should be fairly familiar by now.</p>
<pre class="r"><code>data.clean &lt;- data %&gt;%
  mutate(attitude = exercise.attitude.1 + exercise.attitude.2 + exercise.attitude.3 + exercise.attitude.4 + exercise.attitude.5,
         intention = exercise.intention.1 + exercise.intention.2 + exercise.intention.3 + exercise.intention.4 + exercise.intention.5,
         behaviour = exercise.behaviour.1 + exercise.behaviour.2 + exercise.behaviour.3 + exercise.behaviour.4 + exercise.behaviour.5) %&gt;%
  dplyr::select(student.no,attitude,intention,behaviour) %&gt;%
  filter(!is.na(attitude)) %&gt;%
  filter(!is.na(intention)) %&gt;%
  filter(!is.na(behaviour))</code></pre>
</div>
<div id="run-statistical-test" class="section level3">
<h3>2. Run statistical test</h3>
<p>Remember, mediation is when the effect of one IV could be explained through a third variable (mediation). If there is an effect in a model without the mediator, but that effect is reduced (or disappears) when the mediator is included, there is a chance the mediation is happening. In order to check whether our variables meet these conditions, we need to conduct a number of linear regressions.</p>
<div id="model-1" class="section level4">
<h4>Model 1</h4>
<p>Here, we test whether there is an association between the predictor (attitudes) and the outcome variable (behaviour):</p>
<pre class="r"><code>lm(behaviour ~ attitude,data = data.clean) %&gt;%
  lm.beta() %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = behaviour ~ attitude, data = data.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.4673 -3.4492 -0.5395  3.5689 11.6531 
## 
## Coefficients:
##             Estimate Standardized Std. Error t value Pr(&gt;|t|)    
## (Intercept) 15.44318      0.00000    0.60256  25.629   &lt;2e-16 ***
## attitude     0.02407      0.02776    0.11384   0.211    0.833    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.661 on 58 degrees of freedom
## Multiple R-squared:  0.0007704,  Adjusted R-squared:  -0.01646 
## F-statistic: 0.04472 on 1 and 58 DF,  p-value: 0.8333</code></pre>
</div>
<div id="model-2" class="section level4">
<h4>Model 2</h4>
<p>Here, we test whether including the mediator (intention) in the model changes the relationship between the predictor (attitude) and the outcome variable (behaviour):</p>
<pre class="r"><code>lm(behaviour ~ attitude + intention,data = data.clean) %&gt;%
  lm.beta() %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = behaviour ~ attitude + intention, data = data.clean)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.2548 -3.0644 -0.7116  3.8375 11.0788 
## 
## Coefficients:
##             Estimate Standardized Std. Error t value Pr(&gt;|t|)    
## (Intercept) 15.38806      0.00000    0.60566  25.407   &lt;2e-16 ***
## attitude     0.01627      0.01876    0.11420   0.142    0.887    
## intention    0.14956      0.12665    0.15549   0.962    0.340    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.664 on 57 degrees of freedom
## Multiple R-squared:  0.01673,    Adjusted R-squared:  -0.01777 
## F-statistic: 0.4849 on 2 and 57 DF,  p-value: 0.6183</code></pre>
</div>
<div id="model-3" class="section level4">
<h4>Model 3</h4>
<p>Also, in order for there to be a mediation, we must observe a relationship between the predictor (attitude) and the mediator (intention):</p>
<pre class="r"><code>lm(intention ~ attitude,data = data.clean) %&gt;%
  lm.beta() %&gt;%
  summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = intention ~ attitude, data = data.clean)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.421 -2.590 -0.212  2.788  6.631 
## 
## Coefficients:
##             Estimate Standardized Std. Error t value Pr(&gt;|t|)
## (Intercept)  0.36855      0.00000    0.50917   0.724    0.472
## attitude     0.05219      0.07106    0.09620   0.543    0.590
## 
## Residual standard error: 3.938 on 58 degrees of freedom
## Multiple R-squared:  0.00505,    Adjusted R-squared:  -0.0121 
## F-statistic: 0.2944 on 1 and 58 DF,  p-value: 0.5895</code></pre>
</div>
<div id="mediation-analysis" class="section level4">
<h4>Mediation Analysis</h4>
<p>While we may or may not meet the conditions for a mediation above, we will continue with the analysis to demonstrate the process of conducting a mediation analysis regardless.</p>
<p>In order to conduct a mediation analysis in R, we will load the <code>psych</code> package. If you haven’t installed the <code>psych</code> package yet, make sure to do this before loading the <code>psych</code> package.</p>
<pre class="r"><code>library(psych)</code></pre>
<p>The function that runs the mediation analysis is aptly named <code>mediate()</code>. Like all analysis functions, the <code>mediate()</code> function accepts a formula and a data.frame, but also a couple of options that we will want to change. For the formula, the mediate function takes a specific form, where the mediator is put inside brackets on the right-hand side of the <code>~</code> symbol:</p>
<pre class="r"><code>DV ~ IV + (Mediator)</code></pre>
<p>So for our analysis, the code becomes the following. Note, we also want to set the ‘std’ argument to <code>TRUE</code> to ensure we receive standardised estimates, and the ‘plot’ argument to <code>FALSE</code> so we are only seeing the numeric output (we will see the plot later).</p>
<pre class="r"><code>model &lt;- mediate(behaviour ~ attitude + (intention),data = data.clean,std = TRUE,plot = FALSE)

model</code></pre>
<pre><code>## 
## Mediation/Moderation Analysis 
## Call: mediate(y = behaviour ~ attitude + (intention), data = data.clean, 
##     std = TRUE, plot = FALSE)
## 
## The DV (Y) was  behaviour . The IV (X) was  attitude . The mediating variable(s) =  intention .
## 
## Total effect(c) of  attitude  on  behaviour  =  0.03   S.E. =  0.13  t  =  0.21  df=  58   with p =  0.83
## Direct effect (c&#39;) of  attitude  on  behaviour  removing  intention  =  0.02   S.E. =  0.13  t  =  0.14  df=  57   with p =  0.89
## Indirect effect (ab) of  attitude  on  behaviour  through  intention   =  0.01 
## Mean bootstrapped indirect effect =  0  with standard error =  0.03  Lower CI =  -0.05    Upper CI =  0.06
## R = 0.13 R2 = 0.02   F = 0.48 on 2 and 57 DF   p-value:  0.618 
## 
##  To see the longer output, specify short = FALSE in the print statement or ask for the summary</code></pre>
<p>Most of the information above is what we have encountered previously. The main information we are interested in this output is the line on the mean bootstrapped indirect effect. A large indirect effect (and consequently a greater drop between the total effect and the direct effect) would indicate that mediation is occuring. Since we are bootstrapping, we can tell the significance through confidence intervals. If the range between the lower CI and the upper CI contains zero, then the indirect effect is not significant. If this range does not contain zero, then we have a significant mediation effect.</p>
</div>
</div>
<div id="plot-data" class="section level3">
<h3>3. Plot data</h3>
<div id="path-diagram" class="section level4">
<h4>Path Diagram</h4>
<p>For mediation, there’s no good way to plot the raw data that visualises the mediation. The most common way to visualise a mediated effect is through a path diagram. You can do this directly in the <code>mediate()</code> function by setting the ‘plot’ argument to <code>TRUE</code> or use the <code>mediate.diagram()</code> like below:</p>
<pre class="r"><code>mediate.diagram(model)</code></pre>
<p><img src="9SEM_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
</div>
<div id="write-up-analysis." class="section level3">
<h3>4. Write-up analysis.</h3>
<p>There are several things you need to include when writing up a mediation analysis. Writing up a mediation analysis includes the write-up for each individual models with and without the mediator (Model 1 and Model 2 above - these numbers are also included in the output for the <code>mediate()</code> function), and also the estimated indirect effect and associated confidence intervals. Usually, you would want to accompany the write-up with a path diagram such as the one above. It does not make much sense to write-up the analysis above as we failed to meet the criteria for a mediation in the first instance, but if we were to do it anyway, it may go something like this:</p>
<blockquote>
<p>In the model where attitudes towards exercise predicted variance in exercise behaviour, the effect of exercise attitudes was not significant (beta = 0.03, p = 0.833). When including intention to exercise into the model, the effect of attitudes on behaviour did not change (beta = 0.02, p = 0.887). Mediation analysis revealled a non-significant indirect effect of intentions to exercise on the association between attitudes towards exercise and exercise behaviour (mean bootstrapped indirect effect = 0.02, 95% CI = -0.05, 0.06).</p>
</blockquote>
<p>Note: While we report the results in text above, it is sometimes also easier to report the separate models in a table.</p>
</div>
</div>
<div id="before-we-continue" class="section level2">
<h2>Before We Continue…</h2>
<p>We are about to start using the <code>lavaan</code> package, which is used for path analyses and structural equation models. This workbook is only meant to serve as an introduction to the <code>lavaan</code> package, and therefore we will only discuss some of the basic functions. You are able to add a lot of complexity to structural equation models that we will not be touching. If you truly wish to master this package, you will need to go beyond the content covered here.</p>
</div>
<div id="mediation-analysis-through-structural-equation-modelling-sem" class="section level2">
<h2>Mediation Analysis Through Structural Equation Modelling (SEM)</h2>
<p>Mediation is an example of a simple SEM. We will first re-run the mediation we conducted above in the <code>lavaan</code> package, as this is a handy way of demonstrating the logic of the <code>lavaan</code> package.</p>
<p>As with all analyses, we will be following the basic procedure of:</p>
<ol style="list-style-type: decimal">
<li>Clean the data for analysis.</li>
<li>Run the statistical test.</li>
<li>Plot the data.</li>
<li>Write-up analysis.</li>
</ol>
<div id="clean-the-data-for-analysis." class="section level3">
<h3>1. Clean the data for analysis.</h3>
<p>As always, our first step is to calculate the variables from the individual items.</p>
<p>The code below is identical to the code used for the mediation above.</p>
<pre class="r"><code>data2.clean &lt;- data %&gt;%
  mutate(attitude = exercise.attitude.1 + exercise.attitude.2 + exercise.attitude.3 + exercise.attitude.4 + exercise.attitude.5,
         intention = exercise.intention.1 + exercise.intention.2 + exercise.intention.3 + exercise.intention.4 + exercise.intention.5,
         behaviour = exercise.behaviour.1 + exercise.behaviour.2 + exercise.behaviour.3 + exercise.behaviour.4 + exercise.behaviour.5) %&gt;%
  dplyr::select(student.no,attitude,intention,behaviour) %&gt;%
  filter(!is.na(attitude)) %&gt;%
  filter(!is.na(intention)) %&gt;%
  filter(!is.na(behaviour))</code></pre>
</div>
<div id="run-statistical-test." class="section level3">
<h3>2. Run statistical test.</h3>
<p>Previously, when specifying a regression in R, we have used the following form:</p>
<blockquote>
<p>y ~ x1 + x2 + x3 + …</p>
</blockquote>
<p>An SEM formula is an extention of of this, where multiple regression equations (or similar relationships) are estimated at once. Like with a regression, we use the <code>~</code> to specify a relationship between an outcome (on the left), and predictors (on the right).</p>
<p>In the table below are some other relationships that you may use when constructing a SEM.</p>
<table>
<colgroup>
<col width="9%" />
<col width="18%" />
<col width="20%" />
<col width="52%" />
</colgroup>
<thead>
<tr class="header">
<th>operator</th>
<th>relationship type</th>
<th>example</th>
<th>explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>=~</code></td>
<td>Latent Variable</td>
<td>y =~ x1 + x2 + x3…</td>
<td>y is measured by x1, x2, x3, etc.</td>
</tr>
<tr class="even">
<td><code>~~</code></td>
<td>Covariance</td>
<td>x1 ~~ x2</td>
<td>x1 is correlated with x2</td>
</tr>
<tr class="odd">
<td><code>:=</code></td>
<td>Define Parameter</td>
<td>effect := a*b</td>
<td>Estimate ‘effect’ which is made up of ‘a’ times ‘b’</td>
</tr>
</tbody>
</table>
<p>Note: you can also label parameters by using the <code>*</code> symbol before variables. If you give two variables the same label, it will force the estimates to be the same (this comes in handy sometimes, but not something we will use in this workbook).</p>
<p>Below is the formula to conduct a mediation analysis identical to the one we conducted in Workbook 7. See if you can understand each line and what relationship it is specifying before reading the breakdown. Remember, each line of code can be read as relationships between variables in the model.</p>
<pre class="r"><code>sem.formula &lt;- &#39;
behaviour ~ c*attitude
behaviour ~ b*intention
intention ~ a*attitude

indirect := a*b
direct := c
total := direct + indirect
&#39;</code></pre>
<p>Let’s break this down:</p>
<table>
<colgroup>
<col width="25%" />
<col width="74%" />
</colgroup>
<thead>
<tr class="header">
<th>line</th>
<th>explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>behaviour ~ c*attitude</td>
<td>Behaviour is predicted from attitude, and this relationship is labelled ‘c’</td>
</tr>
<tr class="even">
<td>behaviour ~ b*intention</td>
<td>Behaviour is predicted from intention, and this relationship is labelled ‘b’</td>
</tr>
<tr class="odd">
<td>intention ~ a*attitude</td>
<td>Intention is predicted from attitude, and this relationship is labelled ‘a’</td>
</tr>
<tr class="even">
<td>indirect := a*b</td>
<td>Define a parameter called ‘indirect’ which is made up of ‘a’ times ‘b’</td>
</tr>
<tr class="odd">
<td>direct := c</td>
<td>Define a parameter called ‘direct’ which is made up of ‘c’</td>
</tr>
<tr class="even">
<td>total := direct + indirect</td>
<td>Define the total effect (the combination of direct and indirect effect).</td>
</tr>
</tbody>
</table>
<p>Essentially, the first three lines of the code are identical to running the <code>Model 1</code>, <code>Model 2</code>, and <code>Model 3</code> that we ran above, while the last three lines are like running the <code>mediate()</code> function get estimate the indirect and direct effect.</p>
<p>To run the SEM, we use the <code>sem()</code> function. Like all analyses done previously, we need to specify two things: the formula (which we saved as the object <code>sem.formula</code>) and the data.frame. We also set values for a few other arguments. We set ‘standardized’ to <code>TRUE</code> so that we get standardised estimates, ‘fit.measures’ to <code>TRUE</code> so we get model fit indicators, and ‘rsquare’ to <code>TRUE</code> to get an r-square statistic for the model.</p>
<pre class="r"><code>med.sem.model &lt;- sem(sem.formula,data2.clean)

summary(med.sem.model,standardized = TRUE, fit.measures = TRUE, rsquare = TRUE)</code></pre>
<pre><code>## lavaan 0.6-4 ended normally after 15 iterations
## 
##   Optimization method                           NLMINB
##   Number of free parameters                          5
## 
##   Number of observations                            60
## 
##   Estimator                                         ML
##   Model Fit Test Statistic                       0.000
##   Degrees of freedom                                 0
## 
## Model test baseline model:
## 
##   Minimum Function Test Statistic                1.316
##   Degrees of freedom                                 3
##   P-value                                        0.725
## 
## User model versus baseline model:
## 
##   Comparative Fit Index (CFI)                    1.000
##   Tucker-Lewis Index (TLI)                       1.000
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)               -342.351
##   Loglikelihood unrestricted model (H1)       -342.351
## 
##   Number of free parameters                          5
##   Akaike (AIC)                                 694.702
##   Bayesian (BIC)                               705.174
##   Sample-size adjusted Bayesian (BIC)          689.448
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.000
##   90 Percent Confidence Interval          0.000  0.000
##   P-value RMSEA &lt;= 0.05                             NA
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.000
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard Errors                             Standard
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   behaviour ~                                                           
##     attitude   (c)    0.016    0.111    0.146    0.884    0.016    0.019
##     intention  (b)    0.150    0.152    0.987    0.324    0.150    0.127
##   intention ~                                                           
##     attitude   (a)    0.052    0.095    0.552    0.581    0.052    0.071
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .behaviour        20.663    3.772    5.477    0.000   20.663    0.983
##    .intention        14.994    2.737    5.477    0.000   14.994    0.995
## 
## R-Square:
##                    Estimate
##     behaviour         0.017
##     intention         0.005
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##     indirect          0.008    0.016    0.482    0.630    0.008    0.009
##     direct            0.016    0.111    0.146    0.884    0.016    0.019
##     total             0.024    0.112    0.215    0.830    0.024    0.028</code></pre>
<p>If we compare the results here to mediation, we should see that we get very similar, if not the same, results.</p>
</div>
<div id="plot-the-model." class="section level3">
<h3>3. Plot the model.</h3>
<p>The easiest way to plot a structural equation model is using a path diagram. Unfortunately, this is not easy to do in <code>ggplot2</code>. However, we can use a the <code>semPaths()</code> function from the <code>semPlot</code> package. This function has the advantage of being easy to use - all you need to do is load your model estimated in laavan and specify which paths you want to see (or hide). The disadvantage is that you cannot choose how you layout your path diagram, or customise the look of your diagram. Therefore, in order to create publication worthy graphics, you must use another program.</p>
<pre class="r"><code>semPaths(med.sem.model,whatLabel = &quot;est&quot;,intercept = FALSE,residuals = FALSE)</code></pre>
<p><img src="9SEM_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
</div>
<div id="more-complicated-path-analysis" class="section level2">
<h2>More complicated Path Analysis</h2>
<p>We will now have a go at conducting a more complicated SEM. We will continue investigating the relationship between attitudes to exercise, intentions to exercise, and exercise behaviour, but also now investigate norms surrounding fitness and perceived behavioural control. The model we will fit is based on the Theory of Planned Behaviour, and is depicted below.</p>
<div class="figure">
<img src="images/TPB.png" alt="" />
<p class="caption">Theory of Planned Behaviour</p>
</div>
<p>In words, we predict that attitudes towards exercise, norms about exercise, and perceived behavioural control regarding exercise will predict intention to exercise. In turn, intention to exercise predict exercise behaviour. We also predict that perceived behavioural control regarding exercise will directly predict exercise behaviour.</p>
<div id="clean-the-data-for-analysis.-1" class="section level3">
<h3>1. Clean the data for analysis.</h3>
<p>First, we must calculate the variables from each of the items. Something we have done many times now.</p>
<pre class="r"><code>data2.clean &lt;- data %&gt;%
  mutate(attitude = exercise.attitude.1 + exercise.attitude.2 + exercise.attitude.3 + exercise.attitude.4 + exercise.attitude.5,
         intention = exercise.intention.1 + exercise.intention.2 + exercise.intention.3 + exercise.intention.4 + exercise.intention.5,
         control = exercise.control.1 + exercise.control.2 + exercise.control.3,
         norms = exercise.norms.1 + exercise.norms.2 + exercise.norms.3 + exercise.norms.4 + exercise.norms.5,
         behaviour = exercise.behaviour.1 + exercise.behaviour.2 + exercise.behaviour.3 + exercise.behaviour.4 + exercise.behaviour.5) %&gt;%
  dplyr::select(student.no,attitude,intention,control,norms,behaviour) %&gt;%
  filter(!is.na(attitude)) %&gt;%
  filter(!is.na(intention)) %&gt;%
  filter(!is.na(control)) %&gt;%
  filter(!is.na(norms)) %&gt;%
  filter(!is.na(behaviour))</code></pre>
</div>
<div id="run-statistical-test.-1" class="section level3">
<h3>2. Run statistical test.</h3>
<p>First, we need to specify the model. Below, this model is specified as formula that <code>lavaan</code> can read:</p>
<pre class="r"><code>model &lt;- &#39;
intention ~ attitude + norms + control

norms ~~ attitude
attitude ~~ control
control ~~ norms

behaviour ~ intention + control + attitude
&#39;</code></pre>
<p>To break down the code above: Line 1: Attitudes, norms, and control predict intention. Lines 2 to 4: Covariance between predictors is specified explicitly. Line 5: Intention, control and attitudes predicts behaviour.</p>
<p>We then run the SEM model using the <code>sem()</code> function:</p>
<pre class="r"><code>sem.model &lt;- sem(model,data = data2.clean)
summary(sem.model,standardized = TRUE,fit = TRUE, rsquare = TRUE)</code></pre>
<pre><code>## lavaan 0.6-4 ended normally after 47 iterations
## 
##   Optimization method                           NLMINB
##   Number of free parameters                         14
## 
##   Number of observations                            60
## 
##   Estimator                                         ML
##   Model Fit Test Statistic                       0.366
##   Degrees of freedom                                 1
##   P-value (Chi-square)                           0.545
## 
## Model test baseline model:
## 
##   Minimum Function Test Statistic                4.176
##   Degrees of freedom                                10
##   P-value                                        0.939
## 
## User model versus baseline model:
## 
##   Comparative Fit Index (CFI)                    1.000
##   Tucker-Lewis Index (TLI)                      -0.088
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)               -857.231
##   Loglikelihood unrestricted model (H1)       -857.048
## 
##   Number of free parameters                         14
##   Akaike (AIC)                                1742.463
##   Bayesian (BIC)                              1771.784
##   Sample-size adjusted Bayesian (BIC)         1727.750
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.000
##   90 Percent Confidence Interval          0.000  0.288
##   P-value RMSEA &lt;= 0.05                          0.574
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.020
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard Errors                             Standard
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   intention ~                                                           
##     attitude          0.051    0.094    0.541    0.589    0.051    0.069
##     norms            -0.106    0.129   -0.819    0.413   -0.106   -0.106
##     control           0.035    0.134    0.258    0.796    0.035    0.033
##   behaviour ~                                                           
##     intention         0.148    0.152    0.979    0.328    0.148    0.126
##     control           0.022    0.157    0.138    0.890    0.022    0.018
##     attitude          0.017    0.111    0.151    0.880    0.017    0.019
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitude ~~                                                           
##     norms            -0.561    2.654   -0.211    0.833   -0.561   -0.027
##     control          -0.618    2.561   -0.241    0.809   -0.618   -0.031
##   norms ~~                                                              
##     control          -2.317    1.907   -1.215    0.224   -2.317   -0.159
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .intention        14.790    2.700    5.477    0.000   14.790    0.981
##    .behaviour        20.656    3.771    5.477    0.000   20.656    0.983
##     attitude         27.936    5.100    5.477    0.000   27.936    1.000
##     norms            15.122    2.761    5.477    0.000   15.122    1.000
##     control          14.077    2.570    5.477    0.000   14.077    1.000
## 
## R-Square:
##                    Estimate
##     intention         0.019
##     behaviour         0.017</code></pre>
<p>Notice above in the <code>summary()</code> function, we have included additional arguments to get extra statistics that are helpful when it comes to report the analysis.</p>
</div>
<div id="plot-the-model.-1" class="section level3">
<h3>3. Plot the model.</h3>
<p>Again, we use <code>semPaths()</code> to plot our SEM model. Here, the limitations of not being able to organise the layout of your plot is apparent, though it still may be helpful to visualise your results to help your understanding.</p>
<pre class="r"><code>semPaths(sem.model,whatLabel = &quot;std&quot;,intercept = FALSE,residuals = FALSE)</code></pre>
<p><img src="9SEM_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
</div>
<div id="model-comparisons" class="section level2">
<h2>Model Comparisons</h2>
<p>Model comparisons can be used to help decide which model best explains your data with the fewest number of parameters. As covered in the lecture series, models can only be compared if they are nested (i.e., one model must be contained within the other model). For SEM, using model comparisons is particularly useful to determine the significance of individuals paths.</p>
<p>In the example below, we will compare the model above with a simpler model, where the path between control and behaviour is removed. The formula and code to conducted this slightly simpler model is as follows:</p>
<pre class="r"><code>model2 &lt;- &#39;
intention ~ attitude + norms + control

norms ~~ attitude
attitude ~~ control
control ~~ norms

behaviour ~ intention
&#39;

sem.model2 &lt;- sem(model2,data = data2.clean)

#summary(sem.model2,standardized = TRUE,fit = TRUE, rsquare = TRUE)</code></pre>
<p>Note: we have not run the <code>summary()</code> function above to save on space, but feel free to have a look at it.</p>
<p>Now that we have our two models that we will compare, the function we use is called <code>anova()</code>, not to be confused with <code>aov()</code> that runs a one-way between-subjects ANOVA.</p>
<p>For the <code>anova()</code> function, we simply have to specify the two models we are comparing as the two arguments. This will conduct a chi-square difference test.</p>
<pre class="r"><code>anova(sem.model,sem.model2)</code></pre>
<pre><code>## Chi Square Difference Test
## 
##            Df    AIC    BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)
## sem.model   1 1742.5 1771.8 0.3663                              
## sem.model2  3 1738.5 1763.6 0.4067   0.040419       2       0.98</code></pre>
<pre class="r"><code>mod.com &lt;- anova(sem.model,sem.model2)
mcp &lt;- mod.com$`Pr(&gt;Chisq)`[2]</code></pre>
<p>Above, we find that there is not a significant difference between the two models. Therefore, it does not seem that dropping the path between ‘control’ and ‘behaviour’ significantly reduces model fit. As such, you could be justified in removing this path from the model.</p>
<p>While above, we use the <code>anova()</code> function to test the difference between nested SEM models, we can also use this function to compare models from other functions, such as <code>lm()</code>.</p>
</div>
<div id="introducing-latent-variables" class="section level2">
<h2>Introducing Latent Variables</h2>
<p>Up to now, to calculate variables from individual items, we have been adding each item up. However, we could also compute latent variables, which are the underlying variables that each item is meant to tap into.</p>
<p>For example, we could calculate the latent variable ‘norms’ from each of the individual items.</p>
<pre class="r"><code>attitude.formula &lt;- &#39;
  attitude =~ exercise.attitude.1 + exercise.attitude.2 + exercise.attitude.3 + exercise.attitude.4 + exercise.attitude.5
&#39;

attitude.model &lt;- sem(attitude.formula,data = data)
summary(attitude.model,standardized = TRUE)</code></pre>
<pre><code>## lavaan 0.6-4 ended normally after 67 iterations
## 
##   Optimization method                           NLMINB
##   Number of free parameters                         10
## 
##   Number of observations                            60
## 
##   Estimator                                         ML
##   Model Fit Test Statistic                       1.278
##   Degrees of freedom                                 5
##   P-value (Chi-square)                           0.937
## 
## Parameter Estimates:
## 
##   Information                                 Expected
##   Information saturated (h1) model          Structured
##   Standard Errors                             Standard
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   attitude =~                                                           
##     exercis.tttd.1    1.000                               0.276    0.125
##     exercis.tttd.2    3.859    7.310    0.528    0.598    1.065    0.461
##     exercis.tttd.3    2.523    4.726    0.534    0.593    0.696    0.341
##     exercis.tttd.4    2.657    4.961    0.536    0.592    0.734    0.368
##     exercis.tttd.5    0.108    1.504    0.072    0.943    0.030    0.015
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .exercis.tttd.1    4.785    0.899    5.324    0.000    4.785    0.984
##    .exercis.tttd.2    4.197    1.584    2.649    0.008    4.197    0.787
##    .exercis.tttd.3    3.696    0.907    4.074    0.000    3.696    0.884
##    .exercis.tttd.4    3.445    0.917    3.758    0.000    3.445    0.865
##    .exercis.tttd.5    3.713    0.678    5.475    0.000    3.713    1.000
##     attitude          0.076    0.263    0.290    0.772    1.000    1.000</code></pre>
<pre class="r"><code>semPaths(attitude.model,whatLabel = &quot;std&quot;,intercept = FALSE,residuals = FALSE)</code></pre>
<p><img src="9SEM_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>How about we compute latent variables for all the variables in the TPB model above? Doing something like this may not make a lot of sense: we will end up with a gangly model, and we may not have enough observations to get sensible results, but we can do it do it anyway! For demonstrative purposes… The code is provided below to run this analysis, but this code is not executed, as the output is quite long an unweildy.</p>
<div id="specify-the-model" class="section level3">
<h3>Specify the Model</h3>
<pre class="r"><code>model &lt;- &#39;
  attitude =~ exercise.attitude.1 + exercise.attitude.2 + exercise.attitude.3 + exercise.attitude.4 + exercise.attitude.5
  intention =~ exercise.intention.1 + exercise.intention.2 + exercise.intention.3 + exercise.intention.4 + exercise.intention.5
  control =~ exercise.control.1 + exercise.control.2 + exercise.control.3
  norms =~ exercise.norms.1 + exercise.norms.2 + exercise.norms.3 + exercise.norms.4 + exercise.norms.5
  behaviour =~ exercise.behaviour.1 + exercise.behaviour.2 + exercise.behaviour.3 + exercise.behaviour.4 + exercise.behaviour.5

  intention ~ attitude + norms + control
  behaviour ~ intention + control
&#39;</code></pre>
<p>We won’t run the <code>summary()</code> just now because it is very unwieldy, but we have covered the interpretation of the output above.</p>
<pre class="r"><code>sem.model &lt;- sem(model,data = data)
summary(sem.model,standardized = TRUE,fit = TRUE, rsquare = TRUE)</code></pre>
</div>
</div>
</div>
<div id="plot-the-model" class="section level1">
<h1>Plot the Model</h1>
<p>Again, we can plot the SEM using <code>semPaths()</code>, but this gets pretty messy, given the number of items make up each latent variable.</p>
<pre class="r"><code>load(&quot;files/sem.model.Rdata&quot;)</code></pre>
<pre class="r"><code>semPaths(sem.model,whatLabel = &quot;std&quot;,intercept = FALSE,residuals = FALSE)</code></pre>
<p><img src="9SEM_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
</div>
<div id="exercises-1" class="section level1">
<h1>Exercises</h1>
<p>Now that you’ve completed this week’s workbook, why not give this week’s exercises a go? You can download the interactive exercises by clicking the link below.</p>
<p><a href = "exercises.html">Click here to download this week’s exercises.</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
