<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>HPSP131 - Non-Parametric Tests</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HPSP131</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1intro.html">1. Intro</a>
</li>
<li>
  <a href="2data.html">2. Data 1</a>
</li>
<li>
  <a href="7GLM.html">3. Data 2</a>
</li>
<li>
  <a href="3plot.html">4. Plot</a>
</li>
<li>
  <a href="4LM1.html">5. ttest_ANOVA</a>
</li>
<li>
  <a href="5LM2.html">6. Cor_Reg</a>
</li>
<li>
  <a href="6mod.html">7. Mod</a>
</li>
<li>
  <a href="8sim22.html">8. Pwr_Med</a>
</li>
<li>
  <a href="9SEM.html">9. SEM</a>
</li>
<li>
  <a href="10mixed.html">10. Mixed</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Extra
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="extra_lists.html">Lists, Matrices, and Indexing</a>
    </li>
    <li>
      <a href="extra_joins.html">Joining data.frames</a>
    </li>
    <li>
      <a href="extra_cleaning.html">Cleaning and Data Preparation</a>
    </li>
    <li>
      <a href="extra_chisquare.html">Chi-square Tests</a>
    </li>
    <li>
      <a href="extra_nonparametric.html">Non-parametric Tests</a>
    </li>
    <li>
      <a href="extra_logistic.html">Logistic Regression</a>
    </li>
    <li>
      <a href="extra_functions.html">Custom Functions</a>
    </li>
    <li>
      <a href="extra_simulation.html">Simulations</a>
    </li>
  </ul>
</li>
<li>
  <a href="exercises.html">Exercises</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">HPSP131 - Non-Parametric Tests</h1>

</div>


<p>This page contains extra R content not covered in the demonstrations
and could be considered supplementary to the module. This content is
useful for completing the advanced exercises from Week 5 and focuses on
conducting non-parametric tests in R. As covered in the lecture series,
non-parametric tests are distribution-free tests. They are useful if
your data does not meet the assumptions of the parametric test.</p>
<div id="mann-whitney-u-test" class="section level1">
<h1>Mann-Whitney U Test</h1>
<p>The Mann-Whitney U Test is a non-parametric test for when you have a
categorical IV (with two levels) and a continuous DV. The equivalent
parametric test is an independent-samples t-test. The function that runs
a Mann-Whitney U Test is the <code>wilcox.test()</code> function. It’s a
bit confusing that the Mann-Whitney U Test uses a function with a
different name, but the reason for this is because the Mann-Whitney U
Test is also called the Wilcoxon Rank Sum Test (though I avoid using
this name as it is easily confused with the Wilcoxon Signed Rank
Test).</p>
<p>If we wanted to assess whether cat-people are more introverted than
dog-people in the class dataset using a Mann-Whitney U Test, the code
would look like this:</p>
<div id="prepare-the-data." class="section level3">
<h3>1. Prepare the data.</h3>
<p>This code is identical to that when we prepared the data for an
independent-samples t-test.</p>
<pre class="r"><code>data1.clean &lt;- data %&gt;%
  filter(cat.dog != &quot;both&quot;) %&gt;%
  filter(cat.dog != &quot;neither&quot;) %&gt;%
  filter(cat.dog != &quot;&quot;) %&gt;%
  mutate( introvert = introversion2 + introversion5 + introversion7 + introversion8 + introversion10) %&gt;%
  select(cat.dog,introvert)</code></pre>
</div>
<div id="run-the-statistical-test." class="section level3">
<h3>2. Run the statistical test.</h3>
<p>To conduct a Mann-Whitney U Test, you need to specify the two things
needed for all analysis functions: the formula, and the data.frame.</p>
<pre class="r"><code>wilcox.test(introvert~cat.dog,data = data1.clean)</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  introvert by cat.dog
## W = 137, p-value = 0.04366
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div id="visualise-the-data." class="section level3">
<h3>3. Visualise the data.</h3>
<p>A boxplot is the perfect visualisation for non-parametric tests, as
it visualises the median and the interquartile range. We can combine the
boxplot geom and with the violin geom to also give a visualisation of
the distribution of the data.</p>
<pre class="r"><code>ggplot(data1.clean,aes(x = cat.dog,y = introvert,fill = cat.dog)) +
  geom_violin() +
  geom_boxplot(width = .2) +
  theme_classic() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="extra_nonparametric_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="write-up-analysis." class="section level3">
<h3>4. Write-up analysis.</h3>
<p>To report a Mann-Whitney U test, you will need to include the
following information:</p>
<ul>
<li>The U-statistic from the Mann-Whitney U test.</li>
<li>The p-value from the statistical test.</li>
<li>The medians on the DV for both groups.</li>
</ul>
<p>The U-statistic is the ‘W’ from the output of the
<code>wilcox.test()</code> function. This function also gives you the
p-value. To get the medians, you can use the <code>summarise()</code>
and <code>median()</code> functions:</p>
<pre class="r"><code>data1.summary &lt;- data1.clean %&gt;%
  group_by(cat.dog) %&gt;%
  summarise(introvert_median = median(introvert,na.rm = TRUE))

data1.summary</code></pre>
<pre><code>## # A tibble: 2 × 2
##   cat.dog introvert_median
##   &lt;chr&gt;              &lt;dbl&gt;
## 1 cat                   15
## 2 dog                   12</code></pre>
<p>Therefore, the write-up becomes:</p>
<blockquote>
<p>A Mann-Whitney U test indicated that there was a significant
differences in introversion between cat-people (Mdn = 15) and dog-people
(Mdn = 12), U = 137, p = 0.044.</p>
</blockquote>
</div>
</div>
<div id="wilcoxon-signed-rank-test" class="section level1">
<h1>Wilcoxon Signed Rank Test</h1>
<p>The Wilcoxon Signed Rank Test is a non-parametric test for when you
have a within-subjects categorical IV (with two levels) and a continuous
DV. The equivalent parametric test is an paired-samples t-test.</p>
<p>Let’s re-evaluate the analysis investigating intended alcohol
consumption before and after exposure to the Scottish government’s
drinking guidelines in the class dataset, but this time use the
non-parametric test.</p>
<div id="prepare-the-data-for-analysis." class="section level3">
<h3>1. Prepare the data for analysis.</h3>
<p>Again, this code is identical for when we prepared the data for the
paired-samples t-test.</p>
<pre class="r"><code>data2.clean &lt;- data %&gt;%
  filter(!is.na(pre.drink)) %&gt;%
  filter(!is.na(post.drink)) %&gt;%
  select(student.no,pre.drink,post.drink) %&gt;%
  gather(key = &quot;condition&quot;,value = &quot;alcohol&quot;,pre.drink,post.drink) %&gt;%
  mutate(condition = factor(condition,levels = c(&quot;pre.drink&quot;,&quot;post.drink&quot;)))</code></pre>
</div>
<div id="run-the-statistical-test.-1" class="section level3">
<h3>2. Run the statistical test.</h3>
<p>Similar to how an independent-samples t-test and a paired-samples
t-test use the same function, the Mann-Whitney U Test and the Wilcoxon
Signed Rank Test also use the same function: <code>wilcox.test()</code>.
The difference here is the <code>paired</code> argument must be set to
<code>TRUE</code> - the same as if you were conducting a paired-samples
t-test with the <code>t.test()</code> function.</p>
<p>Therefore, the code becomes:</p>
<pre class="r"><code>wilcox.test(alcohol ~ condition,data2.clean,paired = TRUE)</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  alcohol by condition
## V = 43, p-value = 0.1157
## alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div id="visualise-the-data" class="section level3">
<h3>3. Visualise the Data</h3>
<p>Again, we can use a boxplot and violin plot to visualise the
difference before and after exposure:</p>
<pre class="r"><code>ggplot(data2.clean,aes(x = condition,y = alcohol,fill = condition)) +
  geom_violin() +
  geom_boxplot(width = .2) +
  theme_classic() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="extra_nonparametric_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="write-up-the-analysis." class="section level3">
<h3>4. Write-up the analysis.</h3>
<p>Similar to the Mann-Whitney U test, we require information of the
median for each condition. This code is exactly the same as above:</p>
<pre class="r"><code>data2.summary &lt;- data2.clean %&gt;%
  group_by(condition) %&gt;%
  summarise(introvert_median = median(alcohol,na.rm = TRUE))

data2.summary</code></pre>
<pre><code>## # A tibble: 2 × 2
##   condition  introvert_median
##   &lt;fct&gt;                 &lt;dbl&gt;
## 1 pre.drink                 4
## 2 post.drink                4</code></pre>
<p>We also need the test statistic (W) and the associated p-value. Once
we have all this information, the final write-up looks like this:</p>
<blockquote>
<p>A Wilcoxon signed rank test indicated that there was a
non-significant difference on intended alcohol consumption before (Mdn =
4) and after (Mdn = 4) exposure to the Scottish government’s drinking
guidelines, W = 43, p = 0.116.</p>
</blockquote>
</div>
</div>
<div id="kruskal-wallis-test" class="section level1">
<h1>Kruskal-Wallis Test</h1>
<p>The Kruskal-Wallis test is a non-parametric alternative to the
one-way ANOVA, meaning it is used when you have a categorical IV with
more than 2 groups, and a continuous DV.</p>
<div id="prepare-the-data.-1" class="section level3">
<h3>1. Prepare the data.</h3>
<p>As before, we will demonstrate the Kruskal-Wallis test using the
class dataset by revisiting the question of whether cat-people,
dog-people, those who like both, and those who like neither differ on
introversion. First, we must prepare the data - this code is identical
to that for the one-way ANOVA.</p>
<pre class="r"><code>data3.clean &lt;- data %&gt;%
#  filter(cat.dog != &quot;both&quot;) %&gt;%
#  filter(cat.dog != &quot;neither&quot;) %&gt;%
   filter(cat.dog != &quot;&quot;) %&gt;%
  mutate(introvert = introversion2 + introversion5 + introversion7 + introversion8 + introversion10) %&gt;%
  select(cat.dog,introvert)</code></pre>
</div>
<div id="conduct-the-statistical-test." class="section level3">
<h3>2. Conduct the statistical test.</h3>
<p>The function to conduct the Kruskal-Wallis test is
<code>kruskal.test()</code>. Again, with all statistical test functions,
you need to supply the formula and the data.frame you wish to
analyse.</p>
<pre class="r"><code>kruskal.test(introvert ~ cat.dog,data = data3.clean)</code></pre>
</div>
<div id="visualise-the-data.-1" class="section level3">
<h3>3. Visualise the data.</h3>
<p>Here we can visualise the data using a boxplot and violin plot.</p>
<pre class="r"><code>ggplot(data3.clean,aes(x = cat.dog,y = introvert,fill = cat.dog)) +
  geom_violin() +
  geom_boxplot(width = .2) +
  theme_classic() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="extra_nonparametric_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="write-up-the-analysis.-1" class="section level3">
<h3>4. Write-up the analysis.</h3>
<p>To report a Kruskal-Wallis test, you need the following bits of
information:</p>
<ul>
<li>The test-statistic (chi-square). Note: you should use the chi-square
symbol.</li>
<li>The associated degrees of freedom and p-value.</li>
<li>The medians for each of the groups.</li>
</ul>
<p>The first two points are included in the output of the
<code>kruskal.test()</code> function, and we can use the
<code>summarise()</code> and <code>median()</code> functions to get the
third point:</p>
<pre class="r"><code>data3.summary &lt;- data3.clean %&gt;%
  group_by(cat.dog) %&gt;%
  summarise(introvert_median = median(introvert,na.rm = TRUE))

data3.summary</code></pre>
<pre><code>## # A tibble: 4 × 2
##   cat.dog introvert_median
##   &lt;chr&gt;              &lt;dbl&gt;
## 1 both                  13
## 2 cat                   15
## 3 dog                   12
## 4 neither               13</code></pre>
<p>With this information, you can write-up your results. Remember, much
like with the one-way ANOVA, this Kruskal-Wallis test will tell you
whether the groups are significantly different, but it does not tell you
where those differences are. In order to determine this, you will need
to conduct post-hoc comparisons.</p>
<blockquote>
<p>A Kruskal-Wallis test indicated that there was a non-significant
differences in introversion between cat-people (Mdn = 16), dog-people
(Mdn = 15), those who like both (Mdn = 12), and those who like neither
(Mdn =7.5), Chi-square(3) = 6.07, p = 0.108.</p>
</blockquote>
</div>
</div>
<div id="advanced-exercises" class="section level1">
<h1>Advanced Exercises</h1>
<p>If you would like to practice the skills on this page, weekly
exercise questions on this content are available in the advanced
exercises for Week 5. You can download the interactive exercises by
clicking the link below.</p>
<p><a href = "exercises.html">Click here to download this week’s
exercises.</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
