<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>HPSP131 - Chi-Square Tests</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">HPSP131</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="1intro.html">1. Intro</a>
</li>
<li>
  <a href="2data.html">2. Data 1</a>
</li>
<li>
  <a href="7GLM.html">3. Data 2</a>
</li>
<li>
  <a href="3plot.html">4. Plot</a>
</li>
<li>
  <a href="4LM1.html">5. ttest_ANOVA</a>
</li>
<li>
  <a href="5LM2.html">6. Cor_Reg</a>
</li>
<li>
  <a href="6mod.html">7. Mod</a>
</li>
<li>
  <a href="8sim22.html">8. Pwr_Med</a>
</li>
<li>
  <a href="9SEM.html">9. SEM</a>
</li>
<li>
  <a href="10mixed.html">10. Mixed</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Extra
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="extra_lists.html">Lists, Matrices, and Indexing</a>
    </li>
    <li>
      <a href="extra_joins.html">Joining data.frames</a>
    </li>
    <li>
      <a href="extra_cleaning.html">Cleaning and Data Preparation</a>
    </li>
    <li>
      <a href="extra_chisquare.html">Chi-square Tests</a>
    </li>
    <li>
      <a href="extra_nonparametric.html">Non-parametric Tests</a>
    </li>
    <li>
      <a href="extra_logistic.html">Logistic Regression</a>
    </li>
    <li>
      <a href="extra_functions.html">Custom Functions</a>
    </li>
    <li>
      <a href="extra_simulations.html">Simulations</a>
    </li>
  </ul>
</li>
<li>
  <a href="exercises.html">Exercises</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">HPSP131 - Chi-Square Tests</h1>

</div>


<p>This page contains extra R content not covered in the demonstrations
and could be considered supplementary to the module. This content is
useful for completing the advanced exercises from Week 6 and focuses on
conducting chi-square tests in R. This includes the chi-square goodness
of fit test, and the chi-square test of independence.</p>
<div id="contingency-tables" class="section level1">
<h1>Contingency Tables</h1>
<p>To conduct chi-square tests in R, we use the
<code>chisq.test()</code> function. Unlike most of the statistical
analysis functions we’ve looked at so far, this function does not accept
a formula and a dataset. Instead, the main argument that this function
expects is a contingency table.</p>
<p>To create a contingency table in R, we can use the
<code>table()</code> function. We have briefly talked about the
<code>table()</code> function (to view the frequencies for a single
variable)[<a
href="https://antlee53.github.io/stirpsychstats/2data.html#table"
class="uri">https://antlee53.github.io/stirpsychstats/2data.html#table</a>()_Function],
but as a quick recap, if you wanted to view the frequencies for
favourite Australian animals in the class dataset, the code would
be:</p>
<pre class="r"><code>table(data$aus.animal)</code></pre>
<pre><code>## 
##  echidna kangaroo    koala platypus   wombat 
##        3       12       37       10        5</code></pre>
<p>However, the <code>table()</code> function can also be used to create
a contingency table. A two-variable contingency table will be created
from a data.frame that only has two variables in it. Therefore, you can
use the <code>select()</code> function (covered in Week 3) to create a
data.frame that only includes the two variables that you’re interested
in.</p>
<p>So for example, if we wanted to create a contingency table of
videogamers vs. non-videogamers across the three programmes in the class
dataset, the code would look like this:</p>
<pre class="r"><code>select(data,video.games,program) %&gt;%
  table()</code></pre>
<p>Alternatively, this could be done by inputting two vectors of
variables from the same dataset as arguments. Here is that code:</p>
<pre class="r"><code>table(data$video.games,data$program)</code></pre>
<pre><code>##      
##       Conversion MSc Health MSc Other Research MSc
##   No              20          9                  8
##   Yes             14          8                  8</code></pre>
</div>
<div id="chi-square-goodness-of-fit-test" class="section level1">
<h1>Chi-square Goodness of Fit Test</h1>
<p>As covered in the lecture series, the chi-square goodness of fit test
is used to compare the observed distribution of a single categorical
variable with an expected distribution.</p>
<p>The function that performs a chi-square goodness of fit test is the
<code>chisq.test()</code> function. There are two inputs we require.
First, is a numeric vector with the observed frequencies. Second, is the
probability of the expected frequencies (argument named
<code>p</code>).</p>
<p>For instance, if we conducted a study that counted the frequency of
100 people’s favourite colour, and observed 20 people reported “red”, 35
people reported “green”, and 45 people reported “blue”, then the first
argument would be:</p>
<pre class="r"><code>c(20,35,45)</code></pre>
<pre><code>## [1] 20 35 45</code></pre>
<p>Note: if the variable we are interested in is a variable in a
dataset, then, as described above, we can use the <code>table()</code>
function to get the frequencies.</p>
<p>If we expect an equal distribution among the three colours, our
expected probabilities would be represented as:</p>
<pre class="r"><code>c(1/3,1/3,1/3)</code></pre>
<pre><code>## [1] 0.3333333 0.3333333 0.3333333</code></pre>
<p>Altogether, to conduct the chi-square goodness of fit test, we input
these vectors into the <code>chisq.test()</code> function:</p>
<pre class="r"><code>chisq.test(c(20,35,45),p = c(1/3,1/3,1/3))</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(20, 35, 45)
## X-squared = 9.5, df = 2, p-value = 0.008652</code></pre>
<div id="conduct-the-statistical-test" class="section level3">
<h3>1. Conduct the Statistical Test</h3>
<p>Following the example from the lecture series, let’s conduct a
chi-square goodness of fit test for favourite Australian animals using
the class dataset. We want to compare the frequencies in the class
dataset with the expected proportions form a national UK poll to see if
the class distribution is similar to national rates, or if there’s
something different about this cohort.</p>
<p>To conduct this analysis, we enter the frequencies from the dataset
as the first argument, and a vector with the expected probabilities as
the second argument.</p>
<pre class="r"><code>chisq.test(table(data$aus.animal),p = c(.0171,.2222,.4615,.1624,.1368))</code></pre>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  table(data$aus.animal)
## X-squared = 6.721, df = 4, p-value = 0.1514</code></pre>
</div>
<div id="write-up-the-results" class="section level3">
<h3>2. Write-up the Results</h3>
<p>To report a chi-square test, you need the following information: *
The chi-square statistic (the test statistic). * The degrees of freedom.
* The p-value.</p>
<p>Once you have this information, the write-up becomes:</p>
<blockquote>
<p>A chi-square goodness of fit test did not find a significant
difference between the class distribution of favourite Australian
animals and the expected values based on national rates, chi-square(4) =
6.72, p = 0.151.</p>
</blockquote>
</div>
</div>
<div id="chi-square-test-of-independence" class="section level1">
<h1>Chi-square Test of Independence</h1>
<p>The chi-square test of independence is used to determine if the
distribution of frequencies of a categorical DV are different at
different levels of an IV.</p>
<p>The chi-square test of independence uses the same function as the
chi-square goodness of fit test, but the inputs are different. The
function is smart enough to know which test to conduct given which
inputs it receives.</p>
<div id="conduct-the-statistical-test-1" class="section level3">
<h3>1. Conduct the Statistical Test</h3>
<p>If you input a contingency table that has 2 variables, then the
function knows to conduct a chi-square test of independence. As
described above, contingency tables can be created using the
<code>table()</code> function.</p>
<p>As such, if we were to test whether the proportion of video gamers
was different across the three programmes in the class dataset, the code
looks like this:</p>
<pre class="r"><code>c.table &lt;- select(data,video.games,program) %&gt;%
  table()

chisq.test(c.table)</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  c.table
## X-squared = 0.39057, df = 2, p-value = 0.8226</code></pre>
</div>
<div id="write-up-the-results-1" class="section level3">
<h3>2. Write-up the Results</h3>
<p>To write-up a chi-square test of independence, you need the same
information as above, being the test statistic, the associated degrees
of freedom, and the p-value. Altogether, the write-up then can look
something like this:</p>
<blockquote>
<p>A chi-square test of independence did not find a significant
difference in videogamers across the three programmes, chi-square(2) =
0.39, p = 0.823.</p>
</blockquote>
</div>
</div>
<div id="advanced-exercises" class="section level1">
<h1>Advanced Exercises</h1>
<p>If you would like to practice the skills on this page, weekly
exercise questions on this content are available in the advanced
exercises for Week 6. You can download the interactive exercises by
clicking the link below.</p>
<p><a href = "exercises.html">Click here to download this week’s
exercises.</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
